-- Gardiner signs extracted from the saved EgyptianHieroglyphs.net sign-list page.
-- Rows already present in 002_hieroglyph_data.sql are intentionally omitted.

-- A. Man and his occupations
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓀀', '', '', 'seated man', 'Seated man', 'determinative', 'A1', 'A. Man and his occupations', NULL),
('𓀁', '', '', 'man with hand to mouth', 'Man with hand to mouth', 'determinative', 'A2', 'A. Man and his occupations', NULL),
('𓀂', '', '', 'man sitting on heel', 'Man sitting on heel', 'determinative', 'A3', 'A. Man and his occupations', NULL),
('𓀃', '', '', 'man with arms raised', 'Man with arms raised', 'determinative', 'A4', 'A. Man and his occupations', NULL),
('𓀄', '', '', 'man hiding', 'Man hiding', 'determinative', 'A5', 'A. Man and his occupations', NULL),
('𓀅', '', '', NULL, '', 'other', 'A5a', 'A. Man and his occupations', NULL),
('𓀆', '', '', 'man purifying', 'Man purifying', 'determinative', 'A6', 'A. Man and his occupations', NULL),
('𓀇', '', '', NULL, '', 'other', 'A6a', 'A. Man and his occupations', NULL),
('𓀈', '', '', NULL, '', 'other', 'A6b', 'A. Man and his occupations', NULL),
('𓀉', '', '', 'fatigued man', 'Fatigued man', 'determinative', 'A7', 'A. Man and his occupations', NULL),
('𓀊', '', '', 'man performing hnw', 'Man performing hnw', 'determinative', 'A8', 'A. Man and his occupations', NULL),
('𓀋', '', '', 'man with basket on head', 'Man with basket on head', 'determinative', 'A9', 'A. Man and his occupations', NULL),
('𓀌', '', '', 'man holding an oar', 'Man holding an oar', 'determinative', 'A10', 'A. Man and his occupations', NULL),
('𓀍', '', '', 'man with scepter and crook', 'Man with scepter and crook', 'determinative', 'A11', 'A. Man and his occupations', NULL),
('𓀎', '', '', 'man with bow and quiver', 'Man with bow and quiver', 'determinative', 'A12', 'A. Man and his occupations', NULL),
('𓀏', '', '', 'man with arms bound', 'Man with arms bound', 'determinative', 'A13', 'A. Man and his occupations', NULL),
('𓀐', '', '', 'man with bleeding head', 'Man with bleeding head', 'determinative', 'A14', 'A. Man and his occupations', NULL),
('𓀑', '', '', 'man with axe to head', 'Man with axe to head', 'other', 'A14a', 'A. Man and his occupations', NULL),
('𓀒', '', '', 'man falling', 'Man falling', 'determinative', 'A15', 'A. Man and his occupations', NULL),
('𓀓', '', '', 'man bowing', 'Man bowing', 'determinative', 'A16', 'A. Man and his occupations', NULL),
('𓀔', '', '', 'child with hand to mouth', 'Child with hand to mouth', 'ideographic', 'A17', 'A. Man and his occupations', NULL),
('𓀕', '', '', 'child sitting', 'Child sitting', 'determinative', 'A17a', 'A. Man and his occupations', NULL),
('𓀖', '', '', 'child wearing red crown', 'Child wearing red crown', 'determinative', 'A18', 'A. Man and his occupations', NULL),
('𓀗', '', '', 'aged man bending with stick', 'Aged man bending with stick', 'determinative', 'A19', 'A. Man and his occupations', NULL),
('𓀘', '', '', 'man leaning on forked stick', 'Man leaning on forked stick', 'other', 'A20', 'A. Man and his occupations', NULL),
('𓀙', '', '', 'man with stick', 'Man with stick', 'ideographic', 'A21', 'A. Man and his occupations', NULL),
('𓀚', '', '', 'statue of man with stick and scepter', 'Statue of man with stick and scepter', 'determinative', 'A22', 'A. Man and his occupations', NULL),
('𓀛', '', '', 'king with stick and mace', 'King with stick and mace', 'determinative', 'A23', 'A. Man and his occupations', NULL),
('𓀜', '', '', 'man striking with stick in both hands', 'Man striking with stick in both hands', 'ideographic', 'A24', 'A. Man and his occupations', NULL),
('𓀝', '', '', 'man striking with stick in one hand', 'Man striking with stick in one hand', 'determinative', 'A25', 'A. Man and his occupations', NULL),
('𓀞', '', '', 'man beckoning', 'Man beckoning', 'ideographic', 'A26', 'A. Man and his occupations', NULL),
('𓀟', '', '', 'man running', 'Man running', 'other', 'A27', 'A. Man and his occupations', NULL),
('𓀠', '', '', 'man with arms raised', 'Man with arms raised', 'determinative', 'A28', 'A. Man and his occupations', NULL),
('𓀡', '', '', 'man upside down', 'Man upside down', 'determinative', 'A29', 'A. Man and his occupations', NULL),
('𓀢', '', '', 'man with arms outstretched', 'Man with arms outstretched', 'determinative', 'A30', 'A. Man and his occupations', NULL),
('𓀣', '', '', 'man with arms turned behind him', 'Man with arms turned behind him', 'determinative', 'A31', 'A. Man and his occupations', NULL),
('𓀤', '', '', 'man dancing', 'Man dancing', 'determinative', 'A32', 'A. Man and his occupations', NULL),
('𓀦', '', '', 'man with stick and bundle', 'Man with stick and bundle', 'determinative', 'A33', 'A. Man and his occupations', NULL),
('𓀧', '', '', 'man pounding in a mortar', 'Man pounding in a mortar', 'determinative', 'A34', 'A. Man and his occupations', NULL),
('𓀨', '', '', 'man building a wall', 'Man building a wall', 'ideographic', 'A35', 'A. Man and his occupations', NULL),
('𓀩', '', '', 'man straining into a vessel', 'Man straining into a vessel', 'ideographic', 'A36', 'A. Man and his occupations', NULL),
('𓀪', '', '', 'commoner form a36', 'Commoner form A36', 'other', 'A37', 'A. Man and his occupations', NULL),
('𓀫', '', '', 'man holding two animal emblems', 'Man holding two animal emblems', 'ideographic', 'A38', 'A. Man and his occupations', NULL),
('𓀬', '', '', 'man holding two giraffes', 'Man holding two giraffes', 'other', 'A39', 'A. Man and his occupations', NULL),
('𓀭', '', '', 'seated god', 'Seated god', 'determinative', 'A40', 'A. Man and his occupations', NULL),
('𓀮', '', '', NULL, '', 'other', 'A40a', 'A. Man and his occupations', NULL),
('𓀯', '', '', 'seated king', 'Seated king', 'determinative', 'A41', 'A. Man and his occupations', NULL),
('𓀰', '', '', 'seated king holding flail', 'Seated king holding flail', 'other', 'A42', 'A. Man and his occupations', NULL),
('𓀱', '', '', NULL, '', 'other', 'A42a', 'A. Man and his occupations', NULL),
('𓀲', '', '', 'king wearing white crown of upper egypt', 'King wearing white crown of Upper Egypt', 'determinative', 'A43', 'A. Man and his occupations', NULL),
('𓀳', '', '', NULL, '', 'other', 'A43a', 'A. Man and his occupations', NULL),
('𓀴', '', '', 'king holding flail and wearing white crown of upper egypt', 'King holding flail and wearing white crown of Upper Egypt', 'other', 'A44', 'A. Man and his occupations', NULL),
('𓀵', '', '', 'king wearing red crown of lower egypt.', 'King wearing red crown of Lower Egypt.', 'ideographic', 'A45', 'A. Man and his occupations', NULL),
('𓀶', '', '', NULL, '', 'other', 'A45a', 'A. Man and his occupations', NULL),
('𓀷', '', '', 'king holding flail and wearing red crown of lower egypt.', 'King holding flail and wearing red crown of Lower Egypt.', 'other', 'A46', 'A. Man and his occupations', NULL),
('𓀹', '', '', 'man holding knife', 'Man holding knife', 'determinative', 'A48', 'A. Man and his occupations', NULL),
('𓀺', '', '', 'foreigner with stick', 'Foreigner with stick', 'determinative', 'A49', 'A. Man and his occupations', NULL),
('𓀻', '', '', 'noble seated on chair', 'Noble seated on chair', 'determinative', 'A50', 'A. Man and his occupations', NULL),
('𓀼', '', '', 'noble seated on chair with flagellum', 'Noble seated on chair with flagellum', 'ideographic', 'A51', 'A. Man and his occupations', NULL),
('𓀽', '', '', 'kneeling noble with flail', 'Kneeling noble with flail', 'determinative', 'A52', 'A. Man and his occupations', NULL),
('𓀾', '', '', 'upright mummy', 'Upright mummy', 'determinative', 'A53', 'A. Man and his occupations', NULL),
('𓀿', '', '', 'recumbent mummy', 'Recumbent mummy', 'determinative', 'A54', 'A. Man and his occupations', NULL),
('𓁀', '', '', 'mummy on bed', 'Mummy on bed', 'determinative', 'A55', 'A. Man and his occupations', NULL),
('𓁄', '', '', 'man threatening stick with one hand', 'Man threatening stick with one hand', 'determinative', 'A59', 'A. Man and his occupations', NULL);

-- B. Woman and her occupations
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓁐', '', '', 'seated woman', 'Seated Woman', 'determinative', 'B1', 'B. Woman and her occupations', NULL),
('𓁑', '', '', 'pregnant woman', 'Pregnant woman', 'determinative', 'B2', 'B. Woman and her occupations', NULL),
('𓁒', '', '', 'woman giving birth', 'Woman giving birth', 'ideographic', 'B3', 'B. Woman and her occupations', NULL),
('𓁓', '', '', 'var. b3', 'Var. B3', 'other', 'B4', 'B. Woman and her occupations', NULL),
('𓁔', '', '', 'woman nursing child', 'Woman nursing child', 'determinative', 'B5', 'B. Woman and her occupations', NULL),
('𓁖', '', '', 'woman and seated child', 'Woman and seated child', 'determinative', 'B6', 'B. Woman and her occupations', NULL),
('𓁗', '', '', 'seated queen holding flower', 'Seated queen holding flower', 'determinative', 'B7', 'B. Woman and her occupations', NULL);

-- C. Anthropomorphic deities
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓁚', '', '', 'god with sun-disk and uraeus', 'God with sun-disk and uraeus', 'ideographic', 'C1', 'C. Anthropomorphic deities', NULL),
('𓁜', '', '', 'god with falcon head and sun-disk holding ʿnḫ', 'God with falcon head and sun-disk holding ʿnḫ', 'ideographic', 'C2', 'C. Anthropomorphic deities', NULL),
('𓁟', '', '', 'god with ibis head', 'God with ibis head', 'ideographic', 'C3', 'C. Anthropomorphic deities', NULL),
('𓁠', '', '', 'god with ram head', 'God with ram head', 'ideographic', 'C4', 'C. Anthropomorphic deities', NULL),
('𓁡', '', '', 'god with ram head holding ʿnḫ', 'God with ram head holding ʿnḫ', 'other', 'C5', 'C. Anthropomorphic deities', NULL),
('𓁢', '', '', 'god with jackal head', 'God with jackal head', 'ideographic', 'C6', 'C. Anthropomorphic deities', NULL),
('𓁣', '', '', 'god with seth head', 'God with Seth head', 'ideographic', 'C7', 'C. Anthropomorphic deities', NULL),
('𓁤', '', '', 'min', 'Min', 'ideographic', 'C8', 'C. Anthropomorphic deities', NULL),
('𓁥', '', '', 'goddess with horned sun-disk', 'Goddess with horned sun-disk', 'ideographic', 'C9', 'C. Anthropomorphic deities', NULL),
('𓁦', '', '', 'god with feather', 'God with feather', 'ideographic', 'C10', 'C. Anthropomorphic deities', NULL),
('𓁧', '', '', 'goddess with feather holding ʿnḫ', 'Goddess with feather holding ʿnḫ', 'other', 'C10a', 'C. Anthropomorphic deities', NULL),
('𓁨', '', '', 'ḥḥ-figure', 'ḥḥ-figure', 'ideographic', 'C11', 'C. Anthropomorphic deities', NULL),
('𓁩', '', '', 'amun', 'Amun', 'ideographic', 'C12', 'C. Anthropomorphic deities', NULL),
('𓁮', '', '', 'montu', 'Montu', 'determinative', 'C17', 'C. Anthropomorphic deities', NULL),
('𓁯', '', '', 'tatjenen', 'Tatjenen', 'ideographic', 'C18', 'C. Anthropomorphic deities', NULL),
('𓁰', '', '', 'ptah', 'Ptah', 'ideographic', 'C19', 'C. Anthropomorphic deities', NULL),
('𓁱', '', '', 'variant c19', 'Variant C19', 'other', 'C20', 'C. Anthropomorphic deities', NULL);

-- D. Parts of the human body
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓁸', '', '', 'hair', 'Hair', 'determinative', 'D3', 'D. Parts of the human body', NULL),
('𓁺', '', '', 'eye with paint', 'Eye with paint', 'determinative', 'D5', 'D. Parts of the human body', NULL),
('𓁻', '', '', 'eye with paint', 'Eye with paint', 'other', 'D6', 'D. Parts of the human body', NULL),
('𓁼', '', '', 'eye with paint', 'Eye with paint', 'determinative', 'D7', 'D. Parts of the human body', NULL),
('𓁽', '', '', 'eye enclosed', 'Eye enclosed', 'determinative', 'D8', 'D. Parts of the human body', NULL),
('𓁿', '', '', 'eye weeping', 'Eye weeping', 'ideographic', 'D9', 'D. Parts of the human body', NULL),
('𓂀', '', '', 'eye with falcon’s head marking', 'Eye with falcon’s head marking', 'ideographic', 'D10', 'D. Parts of the human body', NULL),
('𓂁', '', '', 'white part of w3ḏt eye', 'White part of w3ḏt eye', 'other', 'D11', 'D. Parts of the human body', NULL),
('𓂂', '', '', 'eye pupil', 'Eye pupil', 'determinative', 'D12', 'D. Parts of the human body', NULL),
('𓂃', '', '', 'eyebrow', 'Eyebrow', 'other', 'D13', 'D. Parts of the human body', NULL),
('𓂄', '', '', 'white part of w3ḏt eye', 'White part of w3ḏt eye', 'other', 'D14', 'D. Parts of the human body', NULL),
('𓂅', '', '', 'part of w3ḏt eye markings', 'Part of w3ḏt eye markings', 'other', 'D15', 'D. Parts of the human body', NULL),
('𓂆', '', '', 'part of w3ḏt eye markings', 'Part of w3ḏt eye markings', 'other', 'D16', 'D. Parts of the human body', NULL),
('𓂇', '', '', 'markings of w3ḏt eye', 'Markings of w3ḏt eye', 'ideographic', 'D17', 'D. Parts of the human body', NULL),
('𓂈', '', '', 'ear', 'Ear', 'ideographic', 'D18', 'D. Parts of the human body', NULL),
('𓂉', '', '', 'eye, nose, and cheek', 'Eye, nose, and cheek', 'ideographic', 'D19', 'D. Parts of the human body', NULL),
('𓂊', '', '', 'var. d19', 'Var. D19', 'other', 'D20', 'D. Parts of the human body', NULL),
('𓂌', '', '', 'mouth with two lines', 'Mouth with two lines', 'ideographic', 'D22', 'D. Parts of the human body', NULL),
('𓂍', '', '', 'mouth with three lines', 'Mouth with three lines', 'ideographic', 'D23', 'D. Parts of the human body', NULL),
('𓂎', '', '', 'upper lip with teeth', 'Upper lip with teeth', 'ideographic', 'D24', 'D. Parts of the human body', NULL),
('𓂏', '', '', 'lips with teeth', 'Lips with teeth', 'ideographic', 'D25', 'D. Parts of the human body', NULL),
('𓂐', '', '', 'lips spewing water', 'Lips spewing water', 'determinative', 'D26', 'D. Parts of the human body', NULL),
('𓂑', '', '', 'breast', 'Breast', 'determinative', 'D27', 'D. Parts of the human body', NULL),
('𓂒', '', '', 'var. of d27', 'Var. of D27', 'other', 'D27a', 'D. Parts of the human body', NULL),
('𓂔', '', '', 'var. of d28', 'Var. of D28', 'other', 'D29', 'D. Parts of the human body', NULL),
('𓂕', '', '', 'two arms with tail', 'Two arms with tail', 'determinative', 'D30', 'D. Parts of the human body', NULL),
('𓂖', '', '', 'combination of signs d32 and u36', 'Combination of signs D32 and U36', 'ideographic', 'D31', 'D. Parts of the human body', NULL),
('𓂘', '', '', 'two arms embracing', 'Two arms embracing', 'determinative', 'D32', 'D. Parts of the human body', NULL),
('𓂙', 'ẖn', 'Xn', 'arms holding oar', 'Arms holding oar', 'biliteral', 'D33', 'D. Parts of the human body', '𓄡𓈖'),
('𓂚', '', '', 'arms with shield and axe', 'Arms with shield and axe', 'ideographic', 'D34', 'D. Parts of the human body', NULL),
('𓂛', '', '', 'arms with shield and mace', 'Arms with shield and mace', 'other', 'D34a', 'D. Parts of the human body', NULL),
('𓂜', 'n', 'n', 'negative arms', 'Negative arms', 'uniliteral', 'D35', 'D. Parts of the human body', NULL),
('𓂟', 'mỉ', 'mi', 'arm holding bread', 'Arm holding bread', 'biliteral', 'D38', 'D. Parts of the human body', '𓅓𓇋'),
('𓂠', '', '', 'arm holding w24', 'Arm holding W24', 'determinative', 'D39', 'D. Parts of the human body', NULL),
('𓂡', '', '', 'arm holding stick', 'Arm holding stick', 'ideographic', 'D40', 'D. Parts of the human body', NULL),
('𓂢', 'nỉ', 'ni', 'arm with downward facing palm', 'Arm with downward facing palm', 'biliteral', 'D41', 'D. Parts of the human body', '𓈖𓇋'),
('𓂣', '', '', 'arm with downward facing palm', 'Arm with downward facing palm', 'ideographic', 'D42', 'D. Parts of the human body', NULL),
('𓂤', 'ḫw', 'xw', 'arm with flail', 'Arm with flail', 'biliteral', 'D43', 'D. Parts of the human body', '𓐍𓅱'),
('𓂥', '', '', 'arm with scepter', 'Arm with scepter', 'ideographic', 'D44', 'D. Parts of the human body', NULL),
('𓂨', '', '', 'hand with water', 'Hand with water', 'ideographic', 'D46a', 'D. Parts of the human body', NULL),
('𓂩', '', '', 'hand', 'Hand', 'determinative', 'D47', 'D. Parts of the human body', NULL),
('𓂪', '', '', 'palm without thumb', 'Palm without thumb', 'ideographic', 'D48', 'D. Parts of the human body', NULL),
('𓂬', '', '', 'fist', 'Fist', 'determinative', 'D49', 'D. Parts of the human body', NULL),
('𓂭', '', '', 'vertical finger', 'Vertical finger', 'ideographic', 'D50', 'D. Parts of the human body', NULL),
('𓂷', '', '', 'horizontal finger', 'Horizontal finger', 'determinative', 'D51', 'D. Parts of the human body', NULL),
('𓂸', 'mt', 'mt', 'penis', 'Penis', 'biliteral', 'D52', 'D. Parts of the human body', '𓅓𓏏'),
('𓂺', '', '', 'penis with liquid', 'Penis with liquid', 'determinative', 'D53', 'D. Parts of the human body', NULL),
('𓂻', 'ỉw', 'iw', 'legs walking', 'Legs walking', 'biliteral', 'D54', 'D. Parts of the human body', '𓇋𓅱'),
('𓂽', '', '', 'legs walking (reverse of d54)', 'Legs walking (reverse of D54)', 'determinative', 'D55', 'D. Parts of the human body', NULL),
('𓂾', 'pd', 'pd', 'leg', 'Leg', 'biliteral', 'D56', 'D. Parts of the human body', '𓊪𓂧'),
('𓂿', '', '', 'leg with t30', 'Leg with T30', 'determinative', 'D57', 'D. Parts of the human body', NULL),
('𓃁', 'ꜥb', 'Ab', 'foot with d36', 'Foot with D36', 'biliteral', 'D59', 'D. Parts of the human body', '𓂝𓃀'),
('𓃃', '', '', 'toes', 'Toes', 'ideographic', 'D61', 'D. Parts of the human body', NULL),
('𓃄', '', '', 'var. d61', 'Var. D61', 'other', 'D62', 'D. Parts of the human body', NULL),
('𓃅', '', '', 'var. d61', 'Var. D61', 'other', 'D63', 'D. Parts of the human body', NULL);

-- E. Mammals
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓃒', '', '', 'bull', 'Bull', 'ideographic', 'E1', 'E. Mammals', NULL),
('𓃓', '', '', 'bull preparing to charge', 'Bull preparing to charge', 'ideographic', 'E2', 'E. Mammals', NULL),
('𓃔', '', '', 'calf', 'Calf', 'determinative', 'E3', 'E. Mammals', NULL),
('𓃕', '', '', 'sacred cow', 'Sacred cow', 'determinative', 'E4', 'E. Mammals', NULL),
('𓃖', '', '', 'cow with calf', 'Cow with calf', 'determinative', 'E5', 'E. Mammals', NULL),
('𓃗', '', '', 'horse', 'Horse', 'ideographic', 'E6', 'E. Mammals', NULL),
('𓃘', '', '', 'donkey', 'Donkey', 'determinative', 'E7', 'E. Mammals', NULL),
('𓃚', '', '', 'newborn bubalis', 'Newborn bubalis', 'other', 'E9', 'E. Mammals', NULL),
('𓃛', '', '', 'ram', 'Ram', 'determinative', 'E10', 'E. Mammals', NULL),
('𓃞', '', '', 'ram', 'Ram', 'other', 'E11', 'E. Mammals', NULL),
('𓃟', '', '', 'pig', 'Pig', 'determinative', 'E12', 'E. Mammals', NULL),
('𓃠', '', '', 'cat', 'Cat', 'determinative', 'E13', 'E. Mammals', NULL),
('𓃡', '', '', 'dog', 'Dog', 'determinative', 'E14', 'E. Mammals', NULL),
('𓃢', '', '', 'recumbent jackal', 'Recumbent Jackal', 'ideographic', 'E15', 'E. Mammals', NULL),
('𓃣', '', '', 'recumbent jackal on shrine', 'Recumbent Jackal on shrine', 'other', 'E16', 'E. Mammals', NULL),
('𓃥', '', '', 'jackal', 'Jackal', 'ideographic', 'E17', 'E. Mammals', NULL),
('𓃧', '', '', 'jackal on standard r12', 'Jackal on standard R12', 'ideographic', 'E18', 'E. Mammals', NULL),
('𓃨', '', '', 'o.k. form of last', 'O.K. form of last', 'other', 'E19', 'E. Mammals', NULL),
('𓃩', '', '', 'seth animal', 'Seth animal', 'ideographic', 'E20', 'E. Mammals', NULL),
('𓃫', '', '', 'recumbent seth animal', 'Recumbent Seth animal', 'determinative', 'E21', 'E. Mammals', NULL),
('𓃬', '', '', 'lion', 'Lion', 'ideographic', 'E22', 'E. Mammals', NULL),
('𓃭', '', '', 'recumbent lion', 'Recumbent Lion', 'ideographic', 'E23', 'E. Mammals', NULL),
('𓃮', '', '', 'panther', 'Panther', 'ideographic', 'E24', 'E. Mammals', NULL),
('𓃯', '', '', 'hippopotamus', 'Hippopotamus', 'determinative', 'E25', 'E. Mammals', NULL),
('𓃰', '', '', 'elephant', 'Elephant', 'ideographic', 'E26', 'E. Mammals', NULL),
('𓃱', '', '', 'giraffe', 'Giraffe', 'determinative', 'E27', 'E. Mammals', NULL),
('𓃲', '', '', 'oryx', 'Oryx', 'determinative', 'E28', 'E. Mammals', NULL),
('𓃴', '', '', 'gazelle', 'Gazelle', 'determinative', 'E29', 'E. Mammals', NULL),
('𓃵', '', '', 'ibex', 'Ibex', 'determinative', 'E30', 'E. Mammals', NULL),
('𓃶', '', '', 'goat with collar', 'Goat with collar', 'determinative', 'E31', 'E. Mammals', NULL),
('𓃷', '', '', 'baboon', 'Baboon', 'determinative', 'E32', 'E. Mammals', NULL),
('𓃸', '', '', 'monkey', 'Monkey', 'determinative', 'E33', 'E. Mammals', NULL),
('𓃹', 'wn', 'wn', 'hare', 'Hare', 'biliteral', 'E34', 'E. Mammals', '𓅱𓈖');

-- F. Parts of mammals
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓃾', '', '', 'head of ox', 'Head of ox', 'ideographic', 'F1', 'F. Parts of mammals', NULL),
('𓄀', '', '', 'head of charging ox', 'Head of charging ox', 'determinative', 'F2', 'F. Parts of mammals', NULL),
('𓄁', 'ꜣt', 'at', 'head of hippopotamus', 'Head of hippopotamus', 'biliteral', 'F3', 'F. Parts of mammals', '𓄿𓏏'),
('𓄃', '', '', 'head of bubalis', 'Head of bubalis', 'ideographic', 'F5', 'F. Parts of mammals', NULL),
('𓄄', '', '', 'forepart of bubalis', 'Forepart of bubalis', 'other', 'F6', 'F. Parts of mammals', NULL),
('𓄅', '', '', 'head of ram', 'Head of ram', 'ideographic', 'F7', 'F. Parts of mammals', NULL),
('𓄆', '', '', 'forepart of ram', 'Forepart of ram', 'other', 'F8', 'F. Parts of mammals', NULL),
('𓄇', '', '', 'head of leopard', 'Head of leopard', 'ideographic', 'F9', 'F. Parts of mammals', NULL),
('𓄈', '', '', 'head and neck of animal', 'Head and neck of animal', 'determinative', 'F10', 'F. Parts of mammals', NULL),
('𓄉', '', '', 'o.k. form of f10', 'O.K. form of F10', 'other', 'F11', 'F. Parts of mammals', NULL),
('𓄋', '', '', 'horns of ox', 'Horns of ox', 'ideographic', 'F13', 'F. Parts of mammals', NULL),
('𓄍', '', '', 'combination of f13 and m4', 'Combination of F13 and M4', 'ideographic', 'F14', 'F. Parts of mammals', NULL),
('𓄎', '', '', 'combination of f14 and n5', 'Combination of F14 and N5', 'other', 'F15', 'F. Parts of mammals', NULL),
('𓄏', 'ꜥb', 'Ab', 'horn', 'Horn', 'biliteral', 'F16', 'F. Parts of mammals', '𓂝𓃀'),
('𓄐', '', '', 'combination of f16 and d60 water vessel', 'Combination of F16 and D60 water vessel', 'ideographic', 'F17', 'F. Parts of mammals', NULL),
('𓄒', '', '', 'jawbone of ox', 'Jawbone of ox', 'determinative', 'F19', 'F. Parts of mammals', NULL),
('𓄓', 'ns', 'ns', 'tongue', 'Tongue', 'biliteral', 'F20', 'F. Parts of mammals', '𓈖𓋴'),
('𓄖', 'pḥ', 'pH', 'hindquarters of leopard or lion', 'Hindquarters of leopard or lion', 'biliteral', 'F22', 'F. Parts of mammals', '𓊪𓎛'),
('𓄘', '', '', 'reverse of f23', 'Reverse of F23', 'other', 'F24', 'F. Parts of mammals', NULL),
('𓄚', 'ẖn', 'Xn', 'goatskin', 'Goatskin', 'biliteral', 'F26', 'F. Parts of mammals', '𓄡𓈖'),
('𓄛', '', '', 'cowskin', 'Cowskin', 'determinative', 'F27', 'F. Parts of mammals', NULL),
('𓄜', 'sꜣb', 'sab', 'var. of f27', 'Var. of F27', 'triliteral', 'F28', 'F. Parts of mammals', '𓋴𓄿𓃀'),
('𓄞', 'šd', 'Sd', 'water skin', 'Water skin', 'biliteral', 'F30', 'F. Parts of mammals', '𓈙𓂧'),
('𓄢', 'sd', 'sd', 'tail', 'Tail', 'biliteral', 'F33', 'F. Parts of mammals', '𓋴𓂧'),
('𓄣', '', '', 'heart', 'Heart', 'ideographic', 'F34', 'F. Parts of mammals', NULL),
('𓄥', 'smꜣ', 'sma', 'lung and windpipe', 'Lung and windpipe', 'triliteral', 'F36', 'F. Parts of mammals', '𓋴𓅓𓄿'),
('𓄦', '', '', 'backbone and ribs', 'Backbone and ribs', 'ideographic', 'F37', 'F. Parts of mammals', NULL),
('𓄨', '', '', 'var. of f37', 'Var. of F37', 'determinative', 'F38', 'F. Parts of mammals', NULL),
('𓄬', '', '', 'vertebrae', 'Vertebrae', 'determinative', 'F41', 'F. Parts of mammals', NULL),
('𓄭', 'spr', 'spr', 'rib', 'Rib', 'triliteral', 'F42', 'F. Parts of mammals', '𓋴𓊪𓂋'),
('𓄮', '', '', 'ribs', 'Ribs', 'determinative', 'F43', 'F. Parts of mammals', NULL),
('𓄯', 'ỉwꜥ', 'iwA', 'leg bone with meat', 'Leg bone with meat', 'triliteral', 'F44', 'F. Parts of mammals', '𓇋𓅱𓂝'),
('𓄰', '', '', 'heifer uterus', 'Heifer uterus', 'ideographic', 'F45', 'F. Parts of mammals', NULL),
('𓄲', '', '', 'intestine', 'Intestine', 'ideographic', 'F46', 'F. Parts of mammals', NULL),
('𓄴', '', '', 'var. of f46', 'Var. of F46', 'other', 'F47', 'F. Parts of mammals', NULL),
('𓄶', '', '', 'var. of f46', 'Var. of F46', 'other', 'F48', 'F. Parts of mammals', NULL),
('𓄷', '', '', 'var. of f46', 'Var. of F46', 'other', 'F49', 'F. Parts of mammals', NULL),
('𓄸', 'spḫr', 'spxr', 'combination of f46 and s29', 'Combination of F46 and S29', 'other', 'F50', 'F. Parts of mammals', NULL),
('𓄹', 'ỉs', 'is', 'piece of flesh', 'Piece of flesh', 'biliteral', 'F51', 'F. Parts of mammals', '𓇋𓋴'),
('𓄽', '', '', 'excrement', 'Excrement', 'determinative', 'F52', 'F. Parts of mammals', NULL);

-- G. Birds
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓅀', '', '', 'two vultures', 'Two Vultures', 'other', 'G2', 'G. Birds', NULL),
('𓅁', '', '', 'combination of g1 + u1', 'Combination of G1 + U1', 'other', 'G3', 'G. Birds', NULL),
('𓅃', '', '', 'falcon', 'Falcon', 'ideographic', 'G5', 'G. Birds', NULL),
('𓅄', '', '', 'falcon with flail', 'Falcon with flail', 'other', 'G6', 'G. Birds', NULL),
('𓅆', '', '', 'falcon on standard', 'Falcon on standard', 'determinative', 'G7', 'G. Birds', NULL),
('𓅇', '', '', 'var of g7, falcon in boat', 'Var of G7, Falcon in boat', 'ideographic', 'G7a', 'G. Birds', NULL),
('𓅈', '', '', 'var of g7, g7a', 'Var of G7, G7a', 'other', 'G7b', 'G. Birds', NULL),
('𓅉', '', '', 'combination of g5 + s12', 'Combination of G5 + S12', 'ideographic', 'G8', 'G. Birds', NULL),
('𓅊', '', '', 'falcon with sun disk', 'Falcon with sun disk', 'ideographic', 'G9', 'G. Birds', NULL),
('𓅋', '', '', 'falcon in sacred bark', 'Falcon in sacred bark', 'determinative', 'G10', 'G. Birds', NULL),
('𓅌', '', '', 'falcon image', 'Falcon image', 'determinative', 'G11', 'G. Birds', NULL),
('𓅎', '', '', 'falcon image with flail', 'Falcon image with flail', 'other', 'G12', 'G. Birds', NULL),
('𓅏', '', '', 'falcon image with s9', 'Falcon image with S9', 'ideographic', 'G13', 'G. Birds', NULL),
('𓅐', 'mwt', 'mwt', 'vulture', 'Vulture', 'triliteral', 'G14', 'G. Birds', '𓅓𓅱𓏏'),
('𓅑', '', '', 'vulture with flail', 'Vulture with flail', 'determinative', 'G15', 'G. Birds', NULL),
('𓅒', '', '', 'nehkbet and edjo', 'Nehkbet and Edjo', 'ideographic', 'G16', 'G. Birds', NULL),
('𓅔', 'mm', 'mm', 'two owls', 'Two Owls', 'biliteral', 'G18', 'G. Birds', '𓅓𓅓'),
('𓅕', 'mỉ', 'mi', 'combination of g17 + d37', 'Combination of G17 + D37', 'biliteral', 'G19', 'G. Birds', '𓅓𓇋'),
('𓅖', '', '', 'combination of g17 + d36', 'Combination of G17 + D36', 'other', 'G20', 'G. Birds', NULL),
('𓅘', 'nḥ', 'nH', 'guinea fowl', 'Guinea fowl', 'biliteral', 'G21', 'G. Birds', '𓈖𓎛'),
('𓅙', 'ḏb', 'jb', 'hoopoe', 'Hoopoe', 'biliteral', 'G22', 'G. Birds', '𓆓𓃀'),
('𓅚', '', '', 'lapwing', 'Lapwing', 'ideographic', 'G23', 'G. Birds', NULL),
('𓅛', '', '', 'var. of g23', 'Var. of G23', 'other', 'G24', 'G. Birds', NULL),
('𓅜', 'ꜣḫ', 'ax', 'crested ibis', 'Crested Ibis', 'biliteral', 'G25', 'G. Birds', '𓄿𓐍'),
('𓅝', '', '', 'sacred ibis on standard', 'Sacred ibis on standard', 'determinative', 'G26', 'G. Birds', NULL),
('𓅞', '', '', 'sacred ibis', 'Sacred ibis', 'other', 'G26a', 'G. Birds', NULL),
('𓅟', 'dšr', 'dSr', 'flamingo', 'Flamingo', 'triliteral', 'G27', 'G. Birds', '𓂧𓈙𓂋'),
('𓅠', 'gm', 'gm', 'black ibis', 'Black ibis', 'biliteral', 'G28', 'G. Birds', '𓎼𓅓'),
('𓅡', 'bꜣ', 'ba', 'jabiru', 'Jabiru', 'biliteral', 'G29', 'G. Birds', '𓃀𓄿'),
('𓅢', '', '', 'three jabirus', 'Three jabirus', 'ideographic', 'G30', 'G. Birds', NULL),
('𓅣', '', '', 'heron', 'Heron', 'determinative', 'G31', 'G. Birds', NULL),
('𓅤', '', '', 'heron on perch', 'Heron on perch', 'ideographic', 'G32', 'G. Birds', NULL),
('𓅥', '', '', 'egret', 'Egret', 'determinative', 'G33', 'G. Birds', NULL),
('𓅦', '', '', 'ostrich', 'Ostrich', 'determinative', 'G34', 'G. Birds', NULL),
('𓅧', 'ꜥq', 'Aq', 'cormorant', 'Cormorant', 'biliteral', 'G35', 'G. Birds', '𓂝𓈎'),
('𓅨', 'wr', 'wr', 'swallow', 'Swallow', 'biliteral', 'G36', 'G. Birds', '𓅱𓂋'),
('𓅪', '', '', 'sparrow', 'Sparrow', 'determinative', 'G37', 'G. Birds', NULL),
('𓅮', 'pꜣ', 'pa', 'duck flying', 'Duck flying', 'biliteral', 'G40', 'G. Birds', '𓊪𓄿'),
('𓅯', 'ḫn', 'xn', 'duck landing', 'Duck landing', 'biliteral', 'G41', 'G. Birds', '𓐍𓈖'),
('𓅰', '', '', 'fattened bird', 'Fattened bird', 'ideographic', 'G42', 'G. Birds', NULL),
('𓅳', 'ww', 'ww', 'two quail chicks', 'Two quail chicks', 'biliteral', 'G44', 'G. Birds', '𓅱𓅱'),
('𓅴', '', '', 'combination of g43 + d36', 'Combination of G43 + D36', 'other', 'G45', 'G. Birds', NULL),
('𓅶', 'mꜣw', 'maw', 'combination of g43 + u1', 'Combination of G43 + U1', 'triliteral', 'G46', 'G. Birds', '𓅓𓄿𓅱'),
('𓅷', 'ṯꜣ', 'Ta', 'duckling', 'Duckling', 'biliteral', 'G47', 'G. Birds', '𓍿𓄿'),
('𓅸', '', '', 'three ducklings in nest', 'Three ducklings in nest', 'ideographic', 'G48', 'G. Birds', NULL),
('𓅹', '', '', 'ducks’ heads protruding from pool', 'Ducks’ heads protruding from pool', 'ideographic', 'G49', 'G. Birds', NULL),
('𓅺', '', '', 'two plovers', 'Two plovers', 'ideographic', 'G50', 'G. Birds', NULL),
('𓅻', '', '', 'bird pecking fish', 'Bird pecking fish', 'determinative', 'G51', 'G. Birds', NULL),
('𓅼', '', '', 'goose feeding', 'Goose feeding', 'determinative', 'G52', 'G. Birds', NULL),
('𓅽', '', '', 'human headed bird', 'Human headed bird', 'ideographic', 'G53', 'G. Birds', NULL),
('𓅾', 'snḏ', 'snj', 'plucked bird', 'Plucked bird', 'triliteral', 'G54', 'G. Birds', '𓋴𓈖𓆓');

-- H. Parts of birds
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓅿', '', '', 'head of duck', 'Head of duck', 'ideographic', 'H1', 'H. Parts of birds', NULL),
('𓆀', 'mꜣꜥ', 'maA', 'head of crested bird', 'Head of crested bird', 'triliteral', 'H2', 'H. Parts of birds', '𓅓𓄿𓂝'),
('𓆁', 'pꜣq', 'paq', 'head of spoonbill', 'Head of spoonbill', 'triliteral', 'H3', 'H. Parts of birds', '𓊪𓄿𓈎'),
('𓆂', 'nr', 'nr', 'head of vulture', 'Head of vulture', 'biliteral', 'H4', 'H. Parts of birds', '𓈖𓂋'),
('𓆃', '', '', 'wing', 'Wing', 'determinative', 'H5', 'H. Parts of birds', NULL),
('𓆄', 'šw', 'Sw', 'feather', 'Feather', 'biliteral', 'H6', 'H. Parts of birds', '𓈙𓅱'),
('𓆆', 'šꜣ', 'Sa', 'claw', 'Claw', 'biliteral', 'H7', 'H. Parts of birds', '𓈙𓄿'),
('𓆇', '', '', 'egg', 'Egg', 'ideographic', 'H8', 'H. Parts of birds', NULL);

-- I. Amphibious animals, reptiles, etc.
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓆈', 'ꜥšꜣ', 'ASa', 'lizard', 'Lizard', 'triliteral', 'I1', 'I. Amphibious animals, reptiles, etc.', '𓂝𓈙𓄿'),
('𓆉', '', '', 'turtle', 'Turtle', 'ideographic', 'I2', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆊', '', '', 'crocodile', 'Crocodile', 'ideographic', 'I3', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆋', '', '', 'crocodile on shrine', 'Crocodile on shrine', 'determinative', 'I4', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆌', '', '', 'crocodile with curved tail', 'Crocodile with curved tail', 'determinative', 'I5', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆎', 'km', 'km', 'crocodile scales', 'Crocodile scales', 'biliteral', 'I6', 'I. Amphibious animals, reptiles, etc.', '𓎡𓅓'),
('𓆏', '', '', 'frog', 'Frog', 'ideographic', 'I7', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆐', '', '', 'tadpole', 'Tadpole', 'ideographic', 'I8', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆕', '', '', 'two cobras', 'Two cobras', 'other', 'I11', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆗', '', '', 'erect cobra', 'Erect cobra', 'determinative', 'I12', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆘', '', '', 'combination of i12 + v30', 'Combination of I12 + V30', 'determinative', 'I13', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆙', '', '', 'snake', 'Snake', 'determinative', 'I14', 'I. Amphibious animals, reptiles, etc.', NULL),
('𓆚', '', '', 'var. of i15', 'Var. of I15', 'other', 'I15', 'I. Amphibious animals, reptiles, etc.', NULL);

-- K. Fish and parts of fish
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓆜', 'bw', 'bw', 'barbel fish', 'Barbel fish', 'biliteral', 'K2', 'K. Fish and parts of fish', '𓃀𓅱'),
('𓆝', 'ꜥḏ', 'Aj', 'mullet fish', 'Mullet fish', 'biliteral', 'K3', 'K. Fish and parts of fish', '𓂝𓆓'),
('𓆞', 'ẖꜣ', 'Xa', 'oxyrhynchus fish', 'Oxyrhynchus fish', 'biliteral', 'K4', 'K. Fish and parts of fish', '𓄡𓄿'),
('𓆟', 'bs', 'bs', 'pike fish', 'Pike fish', 'biliteral', 'K5', 'K. Fish and parts of fish', '𓃀𓋴'),
('𓆠', '', '', 'fish scale', 'Fish scale', 'ideographic', 'K6', 'K. Fish and parts of fish', NULL),
('𓆡', '', '', 'blowfish', 'Blowfish', 'determinative', 'K7', 'K. Fish and parts of fish', NULL);

-- L. Invertebrates and lesser animals
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓆤', '', '', 'bee', 'Bee', 'ideographic', 'L2', 'L. Invertebrates and lesser animals', NULL),
('𓆦', '', '', 'fly', 'Fly', 'determinative', 'L3', 'L. Invertebrates and lesser animals', NULL),
('𓆧', '', '', 'locust', 'Locust', 'determinative', 'L4', 'L. Invertebrates and lesser animals', NULL),
('𓆨', '', '', 'centipede', 'Centipede', 'determinative', 'L5', 'L. Invertebrates and lesser animals', NULL),
('𓆩', '', '', 'shell', 'Shell', 'other', 'L6', 'L. Invertebrates and lesser animals', NULL),
('𓆫', '', '', 'scorpion', 'Scorpion', 'ideographic', 'L7', 'L. Invertebrates and lesser animals', NULL);

-- M. Trees and plants
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓆭', 'ỉmꜣ', 'ima', 'tree', 'Tree', 'triliteral', 'M1', 'M. Trees and plants', '𓇋𓅓𓄿'),
('𓆰', 'ḥn', 'Hn', 'plant', 'Plant', 'biliteral', 'M2', 'M. Trees and plants', '𓎛𓈖'),
('𓆳', '', '', 'stripped palm branch', 'Stripped palm branch', 'ideographic', 'M4', 'M. Trees and plants', NULL),
('𓆴', '', '', 'combination of m4 + x1', 'Combination of M4 + X1', 'ideographic', 'M5', 'M. Trees and plants', NULL),
('𓆵', '', '', 'combination of m4 + d21', 'Combination of M4 + D21', 'ideographic', 'M6', 'M. Trees and plants', NULL),
('𓆶', '', '', 'combination of m4 + q3', 'Combination of M4 + Q3', 'ideographic', 'M7', 'M. Trees and plants', NULL),
('𓆷', '', '', 'pool with lilies', 'Pool with lilies', 'ideographic', 'M8', 'M. Trees and plants', NULL),
('𓆸', '', '', 'lily', 'Lily', 'determinative', 'M9', 'M. Trees and plants', NULL),
('𓆹', '', '', 'lily bud', 'Lily bud', 'determinative', 'M10', 'M. Trees and plants', NULL),
('𓆻', '', '', 'flower and stem', 'Flower and stem', 'ideographic', 'M11', 'M. Trees and plants', NULL),
('𓇆', 'wꜣḏ', 'waj', 'combination of m13 and i10', 'Combination of M13 and I10', 'triliteral', 'M14', 'M. Trees and plants', '𓅱𓄿𓆓'),
('𓇇', 'ꜣḫ', 'ax', 'papyrus clump with downward facing buds.', 'Papyrus clump with downward facing buds.', 'biliteral', 'M15', 'M. Trees and plants', '𓄿𓐍'),
('𓇉', 'ḥꜣ', 'Ha', 'papyrus clump', 'Papyrus clump', 'biliteral', 'M16', 'M. Trees and plants', '𓎛𓄿'),
('𓇍', '', '', 'combination of m17 + d54', 'Combination of M17 + D54', 'other', 'M18', 'M. Trees and plants', NULL),
('𓇎', '', '', 'conical cakes between signs m17 and u36', 'Conical cakes between signs M17 and U36', 'ideographic', 'M19', 'M. Trees and plants', NULL),
('𓇏', '', '', 'reed field', 'Reed field', 'determinative', 'M20', 'M. Trees and plants', NULL),
('𓇐', '', '', 'reed field with root', 'Reed field with root', 'determinative', 'M21', 'M. Trees and plants', NULL),
('𓇔', '', '', 'combination of m23 + d21', 'Combination of M23 + D21', 'ideographic', 'M24', 'M. Trees and plants', NULL),
('𓇖', '', '', 'combination of m26 + m24', 'Combination of M26 + M24', 'other', 'M25', 'M. Trees and plants', NULL),
('𓇘', 'šmꜥ', 'SmA', 'combination of m26 + d36', 'Combination of M26 + D36', 'triliteral', 'M27', 'M. Trees and plants', '𓈙𓅓𓂝'),
('𓇙', '', '', 'combination of m26 + v20', 'Combination of M26 + V20', 'ideographic', 'M28', 'M. Trees and plants', NULL),
('𓇛', 'nḏm', 'njm', 'pod', 'Pod', 'triliteral', 'M29', 'M. Trees and plants', '𓈖𓆓𓅓'),
('𓇜', '', '', 'root', 'Root', 'ideographic', 'M30', 'M. Trees and plants', NULL),
('𓇝', '', '', 'rhizome', 'Rhizome', 'determinative', 'M31', 'M. Trees and plants', NULL),
('𓇟', '', '', 'var of m31', 'Var of M31', 'other', 'M32', 'M. Trees and plants', NULL),
('𓇠', '', '', 'grain', 'Grain', 'ideographic', 'M33', 'M. Trees and plants', NULL),
('𓇣', '', '', 'emmer sheaf', 'Emmer sheaf', 'ideographic', 'M34', 'M. Trees and plants', NULL),
('𓇤', '', '', 'grain heap', 'Grain heap', 'determinative', 'M35', 'M. Trees and plants', NULL),
('𓇥', 'ḏr', 'jr', 'flax bundle', 'Flax bundle', 'biliteral', 'M36', 'M. Trees and plants', '𓆓𓂋'),
('𓇦', 'ḏr', 'jr', 'flax bundle with stems', 'Flax bundle with stems', 'biliteral', 'M37', 'M. Trees and plants', '𓆓𓂋'),
('𓇧', '', '', 'flax bundle', 'Flax bundle', 'determinative', 'M38', 'M. Trees and plants', NULL),
('𓇩', '', '', 'reed bundle', 'Reed bundle', 'other', 'M40', 'M. Trees and plants', NULL),
('𓇫', '', '', 'wood log', 'Wood log', 'determinative', 'M41', 'M. Trees and plants', NULL),
('𓇬', 'wn', 'wn', 'flower', 'Flower', 'biliteral', 'M42', 'M. Trees and plants', '𓅱𓈖'),
('𓇭', '', '', 'grape vines on props', 'Grape vines on props', 'ideographic', 'M43', 'M. Trees and plants', NULL),
('𓇮', '', '', 'thorn', 'Thorn', 'determinative', 'M44', 'M. Trees and plants', NULL);

-- N. Sky, earth, water
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓇯', '', '', 'sky', 'Sky', 'ideographic', 'N1', 'N. Sky, earth, water', NULL),
('𓇰', '', '', 'sky with broken s40', 'Sky with broken S40', 'ideographic', 'N2', 'N. Sky, earth, water', NULL),
('𓇱', '', '', 'var. of n2', 'Var. of N2', 'other', 'N3', 'N. Sky, earth, water', NULL),
('𓇲', '', '', 'sky with rain', 'Sky with rain', 'ideographic', 'N4', 'N. Sky, earth, water', NULL),
('𓇳', '', '', 'sun', 'Sun', 'ideographic', 'N5', 'N. Sky, earth, water', NULL),
('𓇴', '', '', 'sun with uraeus', 'Sun with uraeus', 'determinative', 'N6', 'N. Sky, earth, water', NULL),
('𓇵', '', '', 'combination of n5 + t28', 'Combination of N5 + T28', 'determinative', 'N7', 'N. Sky, earth, water', NULL),
('𓇶', 'wbn', 'wbn', 'sun with rays', 'Sun with rays', 'triliteral', 'N8', 'N. Sky, earth, water', '𓅱𓃀𓈖'),
('𓇷', 'psḏ', 'psj', 'moon', 'Moon', 'triliteral', 'N9', 'N. Sky, earth, water', '𓊪𓋴𓆓'),
('𓇸', '', '', 'var of n9', 'Var of N9', 'other', 'N10', 'N. Sky, earth, water', NULL),
('𓇹', '', '', 'crescent moon', 'Crescent moon', 'ideographic', 'N11', 'N. Sky, earth, water', NULL),
('𓇺', '', '', 'var. of n11', 'Var. of N11', 'determinative', 'N12', 'N. Sky, earth, water', NULL),
('𓇻', '', '', 'combination of half of n11 and n14', 'Combination of half of N11 and N14', 'ideographic', 'N13', 'N. Sky, earth, water', NULL),
('𓇽', '', '', 'star encircled', 'Star encircled', 'ideographic', 'N15', 'N. Sky, earth, water', NULL),
('𓈀', '', '', 'strip of sand', 'Strip of sand', 'ideographic', 'N18', 'N. Sky, earth, water', NULL),
('𓈃', '', '', 'two strips of sand', 'Two strips of sand', 'ideographic', 'N19', 'N. Sky, earth, water', NULL),
('𓈄', 'wḏb', 'wjb', 'tongue of land', 'Tongue of land', 'triliteral', 'N20', 'N. Sky, earth, water', '𓅱𓆓𓃀'),
('𓈅', '', '', 'tongue of land', 'Tongue of land', 'ideographic', 'N21', 'N. Sky, earth, water', NULL),
('𓈆', '', '', 'tongue of land', 'Tongue of land', 'determinative', 'N22', 'N. Sky, earth, water', NULL),
('𓈇', '', '', 'canal', 'Canal', 'determinative', 'N23', 'N. Sky, earth, water', NULL),
('𓈈', '', '', 'irrigation canal system', 'Irrigation canal system', 'ideographic', 'N24', 'N. Sky, earth, water', NULL),
('𓈉', '', '', 'mountain rande', 'Mountain rande', 'ideographic', 'N25', 'N. Sky, earth, water', NULL),
('𓈌', '', '', 'sunrise over mountain', 'Sunrise over mountain', 'ideographic', 'N27', 'N. Sky, earth, water', NULL),
('𓈏', '', '', 'hill with shrubs', 'Hill with shrubs', 'ideographic', 'N30', 'N. Sky, earth, water', NULL),
('𓈐', '', '', 'road bordered by shrubs', 'Road bordered by shrubs', 'ideographic', 'N31', 'N. Sky, earth, water', NULL),
('𓈑', '', '', 'lump of clay, var. aa2 and f52.', 'Lump of clay, Var. Aa2 and F52.', 'determinative', 'N32', 'N. Sky, earth, water', NULL),
('𓈒', '', '', 'grain of sand', 'Grain of sand', 'determinative', 'N33', 'N. Sky, earth, water', NULL),
('𓈔', '', '', 'metal ingot', 'Metal Ingot', 'ideographic', 'N34', 'N. Sky, earth, water', NULL),
('𓈗', 'mw', 'mw', 'three ripples', 'Three ripples', 'biliteral', 'N35a', 'N. Sky, earth, water', '𓅓𓅱'),
('𓈛', '', '', 'var. of n37', 'Var. of N37', 'other', 'N38', 'N. Sky, earth, water', NULL),
('𓈜', '', '', 'var. of n37', 'Var. of N37', 'other', 'N39', 'N. Sky, earth, water', NULL),
('𓈝', 'šm', 'Sm', 'combination of n37 and d54', 'Combination of N37 and D54', 'biliteral', 'N40', 'N. Sky, earth, water', '𓈙𓅓'),
('𓈟', '', '', 'var. of n41', 'Var. of N41', 'other', 'N42', 'N. Sky, earth, water', NULL);

-- O. Buildings, parts of buildings, etc.
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓉒', '', '', 'combination of o1 + t3', 'Combination of O1 + T3', 'ideographic', 'O2', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉓', '', '', 'combination of o1 + p8 + x3 + w22', 'Combination of O1 + P8 + X3 + W22', 'ideographic', 'O3', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉕', 'nm', 'nm', 'winding wall', 'Winding wall', 'biliteral', 'O5', 'O. Buildings, parts of buildings, etc.', '𓈖𓅓'),
('𓉗', '', '', 'plan of rectangular enclosure', 'Plan of rectangular enclosure', 'ideographic', 'O6', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉞', '', '', 'var of o6', 'Var of O6', 'other', 'O7', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉟', '', '', 'combination of o7 + o29', 'Combination of O7 + O29', 'ideographic', 'O8', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉠', '', '', 'combination of o7 + o30', 'Combination of O7 + O30', 'ideographic', 'O9', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉡', '', '', 'combination of o6 + g5', 'Combination of O6 + G5', 'ideographic', 'O10', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉥', '', '', 'palace with battlements', 'Palace with battlements', 'ideographic', 'O12', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉦', '', '', 'enclosure with battlements', 'Enclosure with battlements', 'determinative', 'O13', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉧', '', '', 'var. of o13', 'Var. of O13', 'other', 'O14', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉨', '', '', 'walled enclosure with buttresses + w10 + x1', 'Walled enclosure with buttresses + W10 + X1', 'ideographic', 'O15', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉩', '', '', 'gateway with serpents', 'Gateway with serpents', 'ideographic', 'O16', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉪', '', '', 'var. of o16', 'Var. of O16', 'other', 'O17', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉫', '', '', 'shrine in profile', 'Shrine in profile', 'ideographic', 'O18', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉬', '', '', 'shrine in profile with poles', 'Shrine in profile with poles', 'determinative', 'O19', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉭', '', '', 'shrine', 'Shrine', 'determinative', 'O20', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉯', '', '', 'shrine facade', 'Shrine Facade', 'ideographic', 'O21', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉱', '', '', 'booth supported by pole', 'Booth supported by pole', 'ideographic', 'O22', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉲', '', '', 'double platform', 'Double platform', 'ideographic', 'O23', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉳', '', '', 'pyramid surrounded by wall', 'Pyramid surrounded by wall', 'determinative', 'O24', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉴', '', '', 'obelisk', 'Obelisk', 'ideographic', 'O25', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉶', '', '', 'stela', 'Stela', 'ideographic', 'O26', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉸', '', '', 'hall with columns', 'Hall with columns', 'determinative', 'O27', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉹', '', '', 'column with tenon', 'Column with tenon', 'other', 'O28', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉺', 'ꜥꜣ', 'Aa', 'wood column', 'Wood column', 'biliteral', 'O29', 'O. Buildings, parts of buildings, etc.', '𓂝𓄿'),
('𓉼', '', '', 'vertical wood column', 'Vertical wood column', 'other', 'O29V', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉽', '', '', 'supporting pole', 'Supporting pole', 'ideographic', 'O30', 'O. Buildings, parts of buildings, etc.', NULL),
('𓉿', '', '', 'door', 'Door', 'determinative', 'O31', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊀', '', '', 'gateway', 'Gateway', 'determinative', 'O32', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊁', '', '', 'palace or tomb facade', 'Palace or tomb facade', 'determinative', 'O33', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊄', 's', 's', 'combination of o34 + d54', 'Combination of O34 + D54', 'uniliteral', 'O35', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊅', '', '', 'wall', 'Wall', 'ideographic', 'O36', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊊', '', '', 'falling wall', 'Falling wall', 'determinative', 'O37', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊋', '', '', 'corner of wall', 'Corner of wall', 'ideographic', 'O38', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊌', '', '', 'stone slab', 'Stone slab', 'determinative', 'O39', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊍', '', '', 'stairway', 'Stairway', 'determinative', 'O40', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊎', '', '', 'double stairway', 'Double stairway', 'determinative', 'O41', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊏', 'šsp', 'Ssp', 'fence', 'Fence', 'triliteral', 'O42', 'O. Buildings, parts of buildings, etc.', '𓈙𓋴𓊪'),
('𓊐', '', '', 'var. of o42', 'Var. of O42', 'other', 'O43', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊑', '', '', 'min emblem', 'Min emblem', 'ideographic', 'O44', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊒', '', '', 'domed building', 'Domed building', 'ideographic', 'O45', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊓', '', '', 'var. of o45', 'Var. of O45', 'other', 'O46', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊔', '', '', 'enclosed mound', 'Enclosed mound', 'ideographic', 'O47', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊕', '', '', 'var. of o47', 'Var. of O47', 'other', 'O48', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊖', '', '', 'area with crossroads', 'Area with crossroads', 'ideographic', 'O49', 'O. Buildings, parts of buildings, etc.', NULL),
('𓊚', '', '', 'grain mound on mud floor', 'Grain mound on mud floor', 'ideographic', 'O51', 'O. Buildings, parts of buildings, etc.', NULL);

-- P. Ships and parts of ships
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓊛', '', '', 'boat on water', 'Boat on water', 'determinative', 'P1', 'P. Ships and parts of ships', NULL),
('𓊜', '', '', 'boat upside down', 'Boat upside down', 'determinative', 'P1a', 'P. Ships and parts of ships', NULL),
('𓊝', '', '', 'ship sailing', 'Ship sailing', 'determinative', 'P2', 'P. Ships and parts of ships', NULL),
('𓊞', '', '', 'sacred bark', 'Sacred bark', 'determinative', 'P3', 'P. Ships and parts of ships', NULL),
('𓊠', 'wḥꜥ', 'wHA', 'boat with net', 'Boat with net', 'triliteral', 'P4', 'P. Ships and parts of ships', '𓅱𓎛𓂝'),
('𓊡', '', '', 'sail', 'Sail', 'ideographic', 'P5', 'P. Ships and parts of ships', NULL),
('𓊢', 'ꜥḥꜥ', 'AHA', 'mast', 'Mast', 'triliteral', 'P6', 'P. Ships and parts of ships', '𓂝𓎛𓂝'),
('𓊣', '', '', 'combination of p6 +d36', 'Combination of P6 +D36', 'other', 'P7', 'P. Ships and parts of ships', NULL),
('𓊥', '', '', 'combination of p8 + i9', 'Combination of P8 + I9', 'other', 'P9', 'P. Ships and parts of ships', NULL),
('𓊦', '', '', 'steering oar', 'Steering oar', 'determinative', 'P10', 'P. Ships and parts of ships', NULL),
('𓊧', '', '', 'mooring post', 'Mooring post', 'determinative', 'P11', 'P. Ships and parts of ships', NULL);

-- Q. Domestics and funerary furniture
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓊩', 'ws', 'ws', 'portable seat', 'Portable seat', 'biliteral', 'Q2', 'Q. Domestics and funerary furniture', '𓅱𓋴'),
('𓊫', '', '', 'headrest', 'Headrest', 'determinative', 'Q4', 'Q. Domestics and funerary furniture', NULL),
('𓊬', '', '', 'chest', 'Chest', 'determinative', 'Q5', 'Q. Domestics and funerary furniture', NULL),
('𓊭', '', '', 'coffin', 'Coffin', 'ideographic', 'Q6', 'Q. Domestics and funerary furniture', NULL),
('𓊮', '', '', 'brazier with flame', 'Brazier with flame', 'determinative', 'Q7', 'Q. Domestics and funerary furniture', NULL);

-- R. Temple furniture and sacred emblems
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓊯', '', '', 'table with jug and loaves', 'Table with jug and loaves', 'ideographic', 'R1', 'R. Temple furniture and sacred emblems', NULL),
('𓊰', '', '', 'table with bread slices', 'Table with bread slices', 'other', 'R2', 'R. Temple furniture and sacred emblems', NULL),
('𓊲', '', '', 'low table with jug and loaves', 'Low table with Jug and loaves', 'ideographic', 'R3', 'R. Temple furniture and sacred emblems', NULL),
('𓊶', '', '', 'censer', 'Censer', 'ideographic', 'R5', 'R. Temple furniture and sacred emblems', NULL),
('𓊷', '', '', 'var. of r5', 'Var. of R5', 'other', 'R6', 'R. Temple furniture and sacred emblems', NULL),
('𓊸', '', '', 'incense bowl', 'Incense bowl', 'ideographic', 'R7', 'R. Temple furniture and sacred emblems', NULL),
('𓊺', '', '', 'combination of r8 + v33', 'Combination of R8 + V33', 'ideographic', 'R9', 'R. Temple furniture and sacred emblems', NULL),
('𓊻', '', '', 'combination of r8 + t28 + n29', 'Combination of R8 + T28 + N29', 'ideographic', 'R10', 'R. Temple furniture and sacred emblems', NULL),
('𓊾', '', '', 'standard', 'Standard', 'determinative', 'R12', 'R. Temple furniture and sacred emblems', NULL),
('𓊿', '', '', 'combination of g5 + r14', 'Combination of G5 + R14', 'ideographic', 'R13', 'R. Temple furniture and sacred emblems', NULL),
('𓋀', '', '', 'var of r13', 'Var of R13', 'ideographic', 'R14', 'R. Temple furniture and sacred emblems', NULL),
('𓋁', '', '', 'spear as standard', 'Spear as standard', 'ideographic', 'R15', 'R. Temple furniture and sacred emblems', NULL),
('𓋂', '', '', 'scepter with feathers', 'Scepter with feathers', 'determinative', 'R16', 'R. Temple furniture and sacred emblems', NULL),
('𓋄', '', '', 'feathered wig with pole', 'Feathered wig with pole', 'ideographic', 'R17', 'R. Temple furniture and sacred emblems', NULL),
('𓋅', '', '', 'var. of r17', 'Var. of R17', 'other', 'R18', 'R. Temple furniture and sacred emblems', NULL),
('𓋆', '', '', 'combination of s40 + feather', 'Combination of S40 + feather', 'determinative', 'R19', 'R. Temple furniture and sacred emblems', NULL),
('𓋇', '', '', 'seshat emblem', 'Seshat emblem', 'ideographic', 'R20', 'R. Temple furniture and sacred emblems', NULL),
('𓋈', '', '', 'var. of r20', 'Var. of R20', 'other', 'R21', 'R. Temple furniture and sacred emblems', NULL),
('𓋊', '', '', 'var. of r22', 'Var. of R22', 'other', 'R23', 'R. Temple furniture and sacred emblems', NULL),
('𓋋', '', '', 'neith emblem', 'Neith emblem', 'determinative', 'R24', 'R. Temple furniture and sacred emblems', NULL),
('𓋌', '', '', 'var. of r24', 'Var. of R24', 'other', 'R25', 'R. Temple furniture and sacred emblems', NULL);

-- S. Crowns, dress, staves, etc.
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓋑', '', '', 'white crown of upper egypt', 'White crown of Upper Egypt', 'ideographic', 'S1', 'S. Crowns, dress, staves, etc.', NULL),
('𓋒', '', '', 'combination of s1 + v30', 'Combination of S1 + V30', 'ideographic', 'S2', 'S. Crowns, dress, staves, etc.', NULL),
('𓋔', 'n', 'n', 'red crown of lower egypt', 'Red crown of Lower Egypt', 'uniliteral', 'S3', 'S. Crowns, dress, staves, etc.', NULL),
('𓋕', '', '', 'combination of s3 + v30', 'Combination of S3 + V30', 'other', 'S4', 'S. Crowns, dress, staves, etc.', NULL),
('𓋖', '', '', 'combination of red and white crown', 'Combination of red and white crown', 'ideographic', 'S5', 'S. Crowns, dress, staves, etc.', NULL),
('𓋗', '', '', 'combination of s5 + v30', 'Combination of S5 + V30', 'other', 'S6', 'S. Crowns, dress, staves, etc.', NULL),
('𓋙', '', '', 'blue crown', 'Blue Crown', 'ideographic', 'S7', 'S. Crowns, dress, staves, etc.', NULL),
('𓋚', '', '', 'atef crown', 'Atef crown', 'ideographic', 'S8', 'S. Crowns, dress, staves, etc.', NULL),
('𓋛', '', '', 'double plumes', 'Double plumes', 'ideographic', 'S9', 'S. Crowns, dress, staves, etc.', NULL),
('𓋜', '', '', 'headband', 'Headband', 'other', 'S10', 'S. Crowns, dress, staves, etc.', NULL),
('𓋝', 'wsḫ', 'wsx', 'collar', 'Collar', 'triliteral', 'S11', 'S. Crowns, dress, staves, etc.', '𓅱𓋴𓐍'),
('𓋟', 'nb', 'nb', 'combination of s12 + d58', 'Combination of S12 + D58', 'biliteral', 'S13', 'S. Crowns, dress, staves, etc.', '𓈖𓃀'),
('𓋠', '', '', 'combination of s12 + t3', 'Combination of S12 + T3', 'ideographic', 'S14', 'S. Crowns, dress, staves, etc.', NULL),
('𓋡', '', '', 'combination of s12 + s40', 'Combination of S12 + S40', 'ideographic', 'S14a', 'S. Crowns, dress, staves, etc.', NULL),
('𓋣', '', '', 'faience pectoral', 'Faience pectoral', 'ideographic', 'S15', 'S. Crowns, dress, staves, etc.', NULL),
('𓋤', '', '', 'var. of s15', 'Var. of S15', 'other', 'S16', 'S. Crowns, dress, staves, etc.', NULL),
('𓋥', '', '', 'var of s15', 'Var of S15', 'other', 'S17', 'S. Crowns, dress, staves, etc.', NULL),
('𓋧', '', '', 'bead necklace', 'Bead necklace', 'ideographic', 'S18', 'S. Crowns, dress, staves, etc.', NULL),
('𓋩', '', '', 'necklace and cylinder seal', 'Necklace and cylinder seal', 'ideographic', 'S20', 'S. Crowns, dress, staves, etc.', NULL),
('𓋪', '', '', 'ring', 'Ring', 'determinative', 'S21', 'S. Crowns, dress, staves, etc.', NULL),
('𓋬', '', '', 'knotted cloth', 'Knotted cloth', 'other', 'S23', 'S. Crowns, dress, staves, etc.', NULL),
('𓋭', 'ṯs', 'Ts', 'knotted belt', 'Knotted belt', 'biliteral', 'S24', 'S. Crowns, dress, staves, etc.', '𓍿𓋴'),
('𓋮', '', '', 'garment with ties', 'Garment with ties', 'ideographic', 'S25', 'S. Crowns, dress, staves, etc.', NULL),
('𓋯', '', '', 'apron', 'Apron', 'ideographic', 'S26', 'S. Crowns, dress, staves, etc.', NULL),
('𓋲', '', '', 'horizontal strips of cloth', 'Horizontal strips of cloth', 'ideographic', 'S27', 'S. Crowns, dress, staves, etc.', NULL),
('𓋳', '', '', 'cloth with fringe + s29', 'Cloth with fringe + S29', 'determinative', 'S28', 'S. Crowns, dress, staves, etc.', NULL),
('𓋵', 'sf', 'sf', 'combination of s29 + i9', 'Combination of S29 + I9', 'biliteral', 'S30', 'S. Crowns, dress, staves, etc.', '𓋴𓆑'),
('𓋶', 'smꜣ', 'sma', 'combination of s29 + u1', 'Combination of S29 + U1', 'triliteral', 'S31', 'S. Crowns, dress, staves, etc.', '𓋴𓅓𓄿'),
('𓋷', 'sỉꜣ', 'sia', 'cloth iwht fringe', 'Cloth iwht fringe', 'triliteral', 'S32', 'S. Crowns, dress, staves, etc.', '𓋴𓇋𓄿'),
('𓋸', '', '', 'sandal', 'Sandal', 'ideographic', 'S33', 'S. Crowns, dress, staves, etc.', NULL),
('𓋺', '', '', 'sunshade', 'Sunshade', 'ideographic', 'S35', 'S. Crowns, dress, staves, etc.', NULL),
('𓋼', '', '', 'var. of s35', 'Var. of S35', 'other', 'S36', 'S. Crowns, dress, staves, etc.', NULL),
('𓋽', '', '', 'fan', 'Fan', 'ideographic', 'S37', 'S. Crowns, dress, staves, etc.', NULL),
('𓋿', '', '', 'crook', 'Crook', 'other', 'S39', 'S. Crowns, dress, staves, etc.', NULL),
('𓌁', 'ḏꜥm', 'jAm', 'scepter with spiral shaft and seth animal', 'Scepter with spiral shaft and Seth animal', 'triliteral', 'S41', 'S. Crowns, dress, staves, etc.', '𓆓𓂝𓅓'),
('𓌂', 'sḫm', 'sxm', 'scepter', 'Scepter', 'triliteral', 'S42', 'S. Crowns, dress, staves, etc.', '𓋴𓐍𓅓'),
('𓌃', 'md', 'md', 'staff', 'Staff', 'biliteral', 'S43', 'S. Crowns, dress, staves, etc.', '𓅓𓂧'),
('𓌄', '', '', 'staff with flail', 'Staff with flail', 'ideographic', 'S44', 'S. Crowns, dress, staves, etc.', NULL),
('𓌅', '', '', 'flail', 'Flail', 'ideographic', 'S45', 'S. Crowns, dress, staves, etc.', NULL);

-- T. Warfare, hunting, and butchery
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓌇', 'mn', 'mn', 'angular headed mace', 'Angular headed mace', 'biliteral', 'T1', 'T. Warfare, hunting, and butchery', '𓅓𓈖'),
('𓌈', '', '', 't3 tilted', 'T3 tilted', 'determinative', 'T2', 'T. Warfare, hunting, and butchery', NULL),
('𓌋', '', '', 'var of t3', 'Var of T3', 'other', 'T4', 'T. Warfare, hunting, and butchery', NULL),
('𓌌', 'ḥḏ', 'Hj', 'combination of t3 + i10', 'Combination of T3 + I10', 'biliteral', 'T5', 'T. Warfare, hunting, and butchery', '𓎛𓆓'),
('𓌍', 'ḥḏḏ', 'Hjj', 'combination of t5 + extra i10', 'Combination of T5 + extra I10', 'triliteral', 'T6', 'T. Warfare, hunting, and butchery', '𓎛𓆓𓆓'),
('𓌎', '', '', 'axe', 'Axe', 'determinative', 'T7', 'T. Warfare, hunting, and butchery', NULL),
('𓌏', '', '', 'axe', 'Axe', 'determinative', 'T7a', 'T. Warfare, hunting, and butchery', NULL),
('𓌑', '', '', 'dagger', 'Dagger', 'determinative', 'T8a', 'T. Warfare, hunting, and butchery', NULL),
('𓌒', 'pd', 'pd', 'bow', 'Bow', 'biliteral', 'T9', 'T. Warfare, hunting, and butchery', '𓊪𓂧'),
('𓌓', '', '', 'var of t9', 'Var of T9', 'other', 'T9a', 'T. Warfare, hunting, and butchery', NULL),
('𓌔', '', '', 'composite bow', 'Composite bow', 'other', 'T10', 'T. Warfare, hunting, and butchery', NULL),
('𓌕', 'swn', 'swn', 'arrow', 'Arrow', 'triliteral', 'T11', 'T. Warfare, hunting, and butchery', '𓋴𓅱𓈖'),
('𓌗', 'rwd', 'rwd', 'bowstring', 'Bowstring', 'triliteral', 'T12', 'T. Warfare, hunting, and butchery', '𓂋𓅱𓂧'),
('𓌘', 'rs', 'rs', 'wood tied together', 'Wood tied together', 'biliteral', 'T13', 'T. Warfare, hunting, and butchery', '𓂋𓋴'),
('𓌙', '', '', 'throw stick', 'Throw stick', 'ideographic', 'T14', 'T. Warfare, hunting, and butchery', NULL),
('𓌚', '', '', 'var. of t14', 'Var. of T14', 'other', 'T15', 'T. Warfare, hunting, and butchery', NULL),
('𓌛', '', '', 'scimitar', 'Scimitar', 'determinative', 'T16', 'T. Warfare, hunting, and butchery', NULL),
('𓌝', '', '', 'chariot', 'Chariot', 'ideographic', 'T17', 'T. Warfare, hunting, and butchery', NULL),
('𓌞', 'šms', 'Sms', 'crook with package', 'Crook with package', 'triliteral', 'T18', 'T. Warfare, hunting, and butchery', '𓈙𓅓𓋴'),
('𓌟', 'qs', 'qs', 'bone harpoon head', 'Bone harpoon head', 'biliteral', 'T19', 'T. Warfare, hunting, and butchery', '𓈎𓋴'),
('𓌠', '', '', 'var. of t19', 'Var. of T19', 'other', 'T20', 'T. Warfare, hunting, and butchery', NULL),
('𓌣', '', '', 'var. of t22', 'Var. of T22', 'other', 'T23', 'T. Warfare, hunting, and butchery', NULL),
('𓌤', 'ꜥḥ', 'AH', 'fishing net', 'Fishing net', 'biliteral', 'T24', 'T. Warfare, hunting, and butchery', '𓂝𓎛'),
('𓌥', 'dbꜣ', 'dba', 'reed float', 'Reed Float', 'triliteral', 'T25', 'T. Warfare, hunting, and butchery', '𓂧𓃀𓄿'),
('𓌦', '', '', 'bird trap', 'Bird Trap', 'ideographic', 'T26', 'T. Warfare, hunting, and butchery', NULL),
('𓌧', '', '', 'var. of t26', 'Var. of T26', 'other', 'T27', 'T. Warfare, hunting, and butchery', NULL),
('𓌩', '', '', 'combination of t28 + t30', 'Combination of T28 + T30', 'ideographic', 'T29', 'T. Warfare, hunting, and butchery', NULL),
('𓌪', '', '', 'knife', 'Knife', 'ideographic', 'T30', 'T. Warfare, hunting, and butchery', NULL),
('𓌫', '', '', 'knife sharpener', 'Knife sharpener', 'other', 'T31', 'T. Warfare, hunting, and butchery', NULL),
('𓌬', '', '', 'combination of t31 + d54', 'Combination of T31 + D54', 'other', 'T32', 'T. Warfare, hunting, and butchery', NULL),
('𓌮', '', '', 'butcher’s knife sharpener', 'Butcher’s knife sharpener', 'ideographic', 'T33', 'T. Warfare, hunting, and butchery', NULL),
('𓌰', 'nm', 'nm', 'butcher’s knife', 'Butcher’s knife', 'biliteral', 'T34', 'T. Warfare, hunting, and butchery', '𓈖𓅓'),
('𓌱', '', '', 'var. of t34', 'Var. of T34', 'other', 'T35', 'T. Warfare, hunting, and butchery', NULL);

-- U. Agriculture, crafts, and professions
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓌴', '', '', 'var. of u1', 'Var. of U1', 'other', 'U2', 'U. Agriculture, crafts, and professions', NULL),
('𓌵', 'mꜣ', 'ma', 'combination of u1 + d4', 'Combination of U1 + D4', 'biliteral', 'U3', 'U. Agriculture, crafts, and professions', '𓅓𓄿'),
('𓌶', 'mꜣꜥ', 'maA', 'combination of u1 + aa11', 'Combination of U1 + Aa11', 'triliteral', 'U4', 'U. Agriculture, crafts, and professions', '𓅓𓄿𓂝'),
('𓌷', '', '', 'var. of u4', 'Var. of U4', 'other', 'U5', 'U. Agriculture, crafts, and professions', NULL),
('𓌸', 'mr', 'mr', 'hoe', 'Hoe', 'biliteral', 'U6', 'U. Agriculture, crafts, and professions', '𓅓𓂋'),
('𓌼', 'ḥn', 'Hn', 'hoe', 'Hoe', 'biliteral', 'U8', 'U. Agriculture, crafts, and professions', '𓎛𓈖'),
('𓌽', '', '', 'grain measure with grain streaming outwards', 'Grain measure with grain streaming outwards', 'determinative', 'U9', 'U. Agriculture, crafts, and professions', NULL),
('𓌾', '', '', 'combination of u9 + m33', 'Combination of U9 + M33', 'ideographic', 'U10', 'U. Agriculture, crafts, and professions', NULL),
('𓌿', '', '', 'combination of s38 + u9', 'Combination of S38 + U9', 'ideographic', 'U11', 'U. Agriculture, crafts, and professions', NULL),
('𓍀', '', '', 'combination of d50 + u9', 'Combination of D50 + U9', 'ideographic', 'U12', 'U. Agriculture, crafts, and professions', NULL),
('𓍂', 'šnꜥ', 'SnA', 'two branches joined', 'Two branches joined', 'triliteral', 'U14', 'U. Agriculture, crafts, and professions', '𓈙𓈖𓂝'),
('𓍄', '', '', 'sled with jackal head bearing a load', 'Sled with jackal head bearing a load', 'determinative', 'U16', 'U. Agriculture, crafts, and professions', NULL),
('𓍅', 'grg', 'grg', 'pick with pool', 'Pick with pool', 'triliteral', 'U17', 'U. Agriculture, crafts, and professions', '𓎼𓂋𓎼'),
('𓍆', '', '', 'var. u17', 'Var. U17', 'other', 'U18', 'U. Agriculture, crafts, and professions', NULL),
('𓍇', 'nw', 'nw', 'adze', 'Adze', 'biliteral', 'U19', 'U. Agriculture, crafts, and professions', '𓈖𓅱'),
('𓍈', '', '', 'var. of u19', 'Var. of U19', 'other', 'U20', 'U. Agriculture, crafts, and professions', NULL),
('𓍊', '', '', 'chisel', 'Chisel', 'determinative', 'U22', 'U. Agriculture, crafts, and professions', NULL),
('𓍍', '', '', 'drill for stone', 'Drill for stone', 'ideographic', 'U24', 'U. Agriculture, crafts, and professions', NULL),
('𓍎', '', '', 'var. of u24', 'Var. of U24', 'other', 'U25', 'U. Agriculture, crafts, and professions', NULL),
('𓍏', '', '', 'drill for beads', 'Drill for beads', 'ideographic', 'U26', 'U. Agriculture, crafts, and professions', NULL),
('𓍐', '', '', 'var. of u26', 'Var. of U26', 'other', 'U27', 'U. Agriculture, crafts, and professions', NULL),
('𓍒', '', '', 'var. of u28', 'Var. of U28', 'other', 'U29', 'U. Agriculture, crafts, and professions', NULL),
('𓍕', '', '', 'baker’s rake', 'Baker’s rake', 'ideographic', 'U31', 'U. Agriculture, crafts, and professions', NULL),
('𓍖', '', '', 'mortar and pestle', 'Mortar and pestle', 'determinative', 'U32', 'U. Agriculture, crafts, and professions', NULL),
('𓍙', 'ḫsf', 'xsf', 'spindle', 'Spindle', 'triliteral', 'U34', 'U. Agriculture, crafts, and professions', '𓐍𓋴𓆑'),
('𓍚', 'ḫsf', 'xsf', 'combination of u34 + i9', 'Combination of U34 + I9', 'triliteral', 'U35', 'U. Agriculture, crafts, and professions', '𓐍𓋴𓆑'),
('𓍜', '', '', 'razor', 'Razor', 'determinative', 'U37', 'U. Agriculture, crafts, and professions', NULL),
('𓍝', '', '', 'scale', 'Scale', 'ideographic', 'U38', 'U. Agriculture, crafts, and professions', NULL),
('𓍞', '', '', 'scale post', 'Scale post', 'determinative', 'U39', 'U. Agriculture, crafts, and professions', NULL),
('𓍟', '', '', 'var. of u39', 'Var. of U39', 'other', 'U40', 'U. Agriculture, crafts, and professions', NULL),
('𓍠', '', '', 'plumb bob', 'Plumb bob', 'determinative', 'U41', 'U. Agriculture, crafts, and professions', NULL);

-- V. Rope, fiber, baskets, bags, etc.
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓍢', 'šn', 'Sn', 'rope coil', 'Rope coil', 'biliteral', 'V1', 'V. Rope, fiber, baskets, bags, etc.', '𓈙𓈖'),
('𓍬', '', '', 'combination of v1 + o34', 'Combination of V1 + O34', 'ideographic', 'V2', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓍮', '', '', 'same as v2, but with two additional coils', 'Same as V2, but with two additional coils', 'ideographic', 'V3', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓍯', 'wꜣ', 'wa', 'lasso', 'Lasso', 'biliteral', 'V4', 'V. Rope, fiber, baskets, bags, etc.', '𓅱𓄿'),
('𓍰', '', '', 'looped rope', 'Looped rope', 'ideographic', 'V5', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓍴', '', '', 'var. of v7', 'Var. of V7', 'other', 'V8', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓍶', '', '', 'round cartouche', 'Round cartouche', 'determinative', 'V9', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓍷', '', '', 'oval cartouche', 'Oval cartouche', 'determinative', 'V10', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓍸', '', '', 'end of cartouche', 'End of cartouche', 'determinative', 'V11', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓍼', '', '', 'string', 'String', 'determinative', 'V12', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎀', '', '', 'var. of v13', 'Var. of V13', 'other', 'V14', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎁', 'ỉṯ', 'iT', 'combination of v13 and d54', 'Combination of V13 and D54', 'biliteral', 'V15', 'V. Rope, fiber, baskets, bags, etc.', '𓇋𓍿'),
('𓎂', 'sꜣ', 'sa', 'hobble for cattle', 'Hobble for cattle', 'biliteral', 'V16', 'V. Rope, fiber, baskets, bags, etc.', '𓋴𓄿'),
('𓎃', '', '', 'herdsman’s shelter', 'Herdsman’s shelter', 'ideographic', 'V17', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎄', '', '', 'var. of v17', 'Var. of V17', 'other', 'V18', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎅', '', '', 'hobble for cattle', 'Hobble for cattle', 'determinative', 'V19', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎆', 'mḏ', 'mj', 'hobble for cattle sans crossbar', 'Hobble for cattle sans crossbar', 'biliteral', 'V20', 'V. Rope, fiber, baskets, bags, etc.', '𓅓𓆓'),
('𓎓', 'mḏ', 'mj', 'combination of v20 + i10', 'Combination of V20 + I10', 'biliteral', 'V21', 'V. Rope, fiber, baskets, bags, etc.', '𓅓𓆓'),
('𓎔', 'mḥ', 'mH', 'whip', 'Whip', 'biliteral', 'V22', 'V. Rope, fiber, baskets, bags, etc.', '𓅓𓎛'),
('𓎕', '', '', 'var. of v22', 'Var. of V22', 'other', 'V23', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎗', 'wḏ', 'wj', 'cord on stick', 'Cord on Stick', 'biliteral', 'V24', 'V. Rope, fiber, baskets, bags, etc.', '𓅱𓆓'),
('𓎘', '', '', 'var. of v24', 'Var. of V24', 'other', 'V25', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎙', 'ꜥd', 'Ad', 'spool with thread', 'Spool with thread', 'biliteral', 'V26', 'V. Rope, fiber, baskets, bags, etc.', '𓂝𓂧'),
('𓎚', '', '', 'var. of v26', 'Var. of V26', 'other', 'V27', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎝', 'wꜣḥ', 'waH', 'swab', 'Swab', 'triliteral', 'V29', 'V. Rope, fiber, baskets, bags, etc.', '𓅱𓄿𓎛'),
('𓎢', '', '', 'v31 reversed', 'V31 reversed', 'other', 'V31a', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎣', 'msn', 'msn', 'wicker satchel', 'Wicker satchel', 'triliteral', 'V32', 'V. Rope, fiber, baskets, bags, etc.', '𓅓𓋴𓈖'),
('𓎤', '', '', 'linen bag', 'Linen bag', 'determinative', 'V33', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎥', '', '', 'var. of v33', 'Var. of V33', 'other', 'V34', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎧', '', '', 'var. of v33', 'Var. of V33', 'other', 'V35', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎨', 'ḥn', 'Hn', 'receptacle', 'Receptacle', 'biliteral', 'V36', 'V. Rope, fiber, baskets, bags, etc.', '𓎛𓈖'),
('𓎩', '', '', 'bandage', 'Bandage', 'ideographic', 'V37', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎫', '', '', 'bandage', 'Bandage', 'determinative', 'V38', 'V. Rope, fiber, baskets, bags, etc.', NULL),
('𓎬', '', '', 'tie', 'Tie', 'ideographic', 'V39', 'V. Rope, fiber, baskets, bags, etc.', NULL);

-- W. Vessels of stone and earthenware
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓎯', '', '', 'oil jar', 'Oil jar', 'determinative', 'W1', 'W. Vessels of stone and earthenware', NULL),
('𓎰', 'bꜣs', 'bas', 'oil jar without ties', 'Oil jar without ties', 'triliteral', 'W2', 'W. Vessels of stone and earthenware', '𓃀𓄿𓋴'),
('𓎱', '', '', 'alabaster basin', 'Alabaster basin', 'ideographic', 'W3', 'W. Vessels of stone and earthenware', NULL),
('𓎳', '', '', 'combination of w3 + o22', 'Combination of W3 + O22', 'ideographic', 'W4', 'W. Vessels of stone and earthenware', NULL),
('𓎴', '', '', 'combination of w3 + t28', 'Combination of W3 + T28', 'other', 'W5', 'W. Vessels of stone and earthenware', NULL),
('𓎵', '', '', 'vessel', 'Vessel', 'determinative', 'W6', 'W. Vessels of stone and earthenware', NULL),
('𓎶', '', '', 'granite bowl', 'Granite bowl', 'determinative', 'W7', 'W. Vessels of stone and earthenware', NULL),
('𓎷', '', '', 'var. of w7', 'Var. of W7', 'other', 'W8', 'W. Vessels of stone and earthenware', NULL),
('𓎺', 'ḥnw', 'Hnw', 'cup', 'Cup', 'triliteral', 'W10', 'W. Vessels of stone and earthenware', '𓎛𓈖𓅱'),
('𓎻', 'bꜣ', 'ba', 'pot', 'Pot', 'biliteral', 'W10a', 'W. Vessels of stone and earthenware', '𓃀𓄿'),
('𓎽', '', '', 'ring stand', 'Ring stand', 'other', 'W12', 'W. Vessels of stone and earthenware', NULL),
('𓎾', '', '', 'pot', 'Pot', 'ideographic', 'W13', 'W. Vessels of stone and earthenware', NULL),
('𓏁', '', '', 'tall jar with water', 'Tall jar with water', 'ideographic', 'W15', 'W. Vessels of stone and earthenware', NULL),
('𓏇', 'mỉ', 'mi', 'milk jug', 'Milk jug', 'biliteral', 'W19', 'W. Vessels of stone and earthenware', '𓅓𓇋'),
('𓏈', '', '', 'milk jug with leaf', 'Milk jug with leaf', 'determinative', 'W20', 'W. Vessels of stone and earthenware', NULL),
('𓏉', '', '', 'wine jars', 'Wine jars', 'determinative', 'W21', 'W. Vessels of stone and earthenware', NULL),
('𓏊', '', '', 'beer jugs', 'Beer jugs', 'ideographic', 'W22', 'W. Vessels of stone and earthenware', NULL),
('𓏋', '', '', 'jug with handles', 'Jug with handles', 'other', 'W23', 'W. Vessels of stone and earthenware', NULL);

-- X. Loaves and cakes
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓏐', '', '', 'tall bread loaf', 'Tall bread loaf', 'ideographic', 'X2', 'X. Loaves and cakes', NULL),
('𓏑', '', '', 'var. of x2', 'Var. of X2', 'other', 'X3', 'X. Loaves and cakes', NULL),
('𓏒', '', '', 'bread roll', 'Bread roll', 'determinative', 'X4', 'X. Loaves and cakes', NULL),
('𓏕', '', '', 'var. of x4', 'Var. of X4', 'determinative', 'X5', 'X. Loaves and cakes', NULL),
('𓏖', '', '', 'round loaf with baker’s mark', 'Round loaf with baker’s mark', 'determinative', 'X6', 'X. Loaves and cakes', NULL),
('𓏘', '', '', 'half loaf of bread', 'Half loaf of bread', 'determinative', 'X7', 'X. Loaves and cakes', NULL);

-- Y. Writings, games, music
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓏛', 'mḏꜣt', 'mjat', 'papyrus scroll', 'Papyrus scroll', 'other', 'Y1', 'Y. Writings, games, music', NULL),
('𓏜', '', '', 'papyrus scroll (vertical)', 'Papyrus scroll (vertical)', 'other', 'Y1v', 'Y. Writings, games, music', NULL),
('𓏝', '', '', 'var. of y1', 'Var. of Y1', 'other', 'Y2', 'Y. Writings, games, music', NULL),
('𓏞', '', '', 'scribal kit', 'Scribal kit', 'ideographic', 'Y3', 'Y. Writings, games, music', NULL),
('𓏟', '', '', 'y4 reversed', 'Y4 reversed', 'other', 'Y4', 'Y. Writings, games, music', NULL),
('𓏡', '', '', 'game piece', 'Game piece', 'ideographic', 'Y6', 'Y. Writings, games, music', NULL),
('𓏢', '', '', 'harp', 'Harp', 'determinative', 'Y7', 'Y. Writings, games, music', NULL),
('𓏣', '', '', 'sistrum', 'Sistrum', 'determinative', 'Y8', 'Y. Writings, games, music', NULL);

-- Z. Strokes, signs derived from Hieratic, geometrical figures
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓏤', '', '', 'stroke', 'Stroke', 'ideographic', 'Z1', 'Z. Strokes, signs derived from Hieratic, geometrical figures', NULL),
('𓏥', '', '', 'triple stroke', 'Triple stroke', 'determinative', 'Z2', 'Z. Strokes, signs derived from Hieratic, geometrical figures', NULL),
('𓏪', '', '', 'three z1 vertical strokes', 'Three Z1 vertical strokes', 'other', 'Z3', 'Z. Strokes, signs derived from Hieratic, geometrical figures', NULL),
('𓏫', '', '', 'z2 vertical', 'Z2 vertical', 'other', 'Z3a', 'Z. Strokes, signs derived from Hieratic, geometrical figures', NULL),
('𓏮', '', '', 'two vertical strokes', 'Two vertical strokes', 'determinative', 'Z4a', 'Z. Strokes, signs derived from Hieratic, geometrical figures', NULL),
('𓏯', '', '', 'diagonal stroke in hieratic', 'Diagonal stroke in hieratic', 'other', 'Z5', 'Z. Strokes, signs derived from Hieratic, geometrical figures', NULL),
('𓏱', '', '', 'hieratic var. of a13 and a14', 'Hieratic var. of A13 and A14', 'determinative', 'Z6', 'Z. Strokes, signs derived from Hieratic, geometrical figures', NULL),
('𓏳', '', '', 'oval', 'Oval', 'determinative', 'Z8', 'Z. Strokes, signs derived from Hieratic, geometrical figures', NULL),
('𓏴', 'swꜣ', 'swa', 'crossed sticks', 'Crossed sticks', 'triliteral', 'Z9', 'Z. Strokes, signs derived from Hieratic, geometrical figures', '𓋴𓅱𓄿'),
('𓏵', '', '', 'var. of z9', 'Var. of Z9', 'other', 'Z10', 'Z. Strokes, signs derived from Hieratic, geometrical figures', NULL),
('𓏶', 'ỉm', 'im', 'crossed planks', 'Crossed planks', 'biliteral', 'Z11', 'Z. Strokes, signs derived from Hieratic, geometrical figures', '𓇋𓅓');

-- Aa. Unclassified
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓐎', '', '', 'pustule or gland?', 'Pustule or gland?', 'determinative', 'Aa2', 'Aa. Unclassified', NULL),
('𓐏', '', '', 'aa2 with substance issuing', 'Aa2 with substance issuing', 'other', 'Aa3', 'Aa. Unclassified', NULL),
('𓐐', '', '', 'pot', 'Pot', 'other', 'Aa4', 'Aa. Unclassified', NULL),
('𓐑', 'ḥp', 'Hp', 'part of ship?', 'Part of ship?', 'biliteral', 'Aa5', 'Aa. Unclassified', '𓎛𓊪'),
('𓐒', '', '', 'unknown', 'Unknown', 'determinative', 'Aa6', 'Aa. Unclassified', NULL),
('𓐓', '', '', 'unknown', 'Unknown', 'determinative', 'Aa7', 'Aa. Unclassified', NULL),
('𓐖', 'qn', 'qn', 'irrigation canal?', 'Irrigation canal?', 'biliteral', 'Aa8', 'Aa. Unclassified', '𓈎𓈖'),
('𓐗', '', '', 'unknown', 'Unknown', 'determinative', 'Aa9', 'Aa. Unclassified', NULL),
('𓐘', '', '', 'unknown', 'Unknown', 'determinative', 'Aa10', 'Aa. Unclassified', NULL),
('𓐚', '', '', 'unknown', 'Unknown', 'other', 'Aa12', 'Aa. Unclassified', NULL),
('𓐛', 'ỉm', 'im', 'unknown', 'Unknown', 'biliteral', 'Aa13', 'Aa. Unclassified', '𓇋𓅓'),
('𓐜', 'ỉm', 'im', 'unknown', 'Unknown', 'biliteral', 'Aa14', 'Aa. Unclassified', '𓇋𓅓'),
('𓐝', 'ỉm', 'im', 'var. aa13', 'Var. Aa13', 'biliteral', 'Aa15', 'Aa. Unclassified', '𓇋𓅓'),
('𓐞', 'gs', 'gs', 'short form aa13', 'Short form Aa13', 'biliteral', 'Aa16', 'Aa. Unclassified', '𓎼𓋴'),
('𓐟', 'sꜣ', 'sa', 'back of something?', 'Back of something?', 'biliteral', 'Aa17', 'Aa. Unclassified', '𓋴𓄿'),
('𓐠', '', '', 'var. of aa17', 'Var. of Aa17', 'other', 'Aa18', 'Aa. Unclassified', NULL),
('𓐡', '', '', 'unknown', 'Unknown', 'determinative', 'Aa19', 'Aa. Unclassified', NULL),
('𓐢', 'ꜥpr', 'Apr', 'unknown', 'Unknown', 'triliteral', 'Aa20', 'Aa. Unclassified', '𓂝𓊪𓂋'),
('𓐣', 'wḏꜥ', 'wjA', 'unknown', 'Unknown', 'triliteral', 'Aa21', 'Aa. Unclassified', '𓅱𓆓𓂝'),
('𓐤', '', '', 'combination of aa21 + d36', 'Combination of Aa21 + D36', 'other', 'Aa22', 'Aa. Unclassified', NULL),
('𓐥', '', '', 'warp between stakes?', 'Warp between stakes?', 'determinative', 'Aa23', 'Aa. Unclassified', NULL),
('𓐦', '', '', 'var. aa23', 'Var. Aa23', 'other', 'Aa24', 'Aa. Unclassified', NULL),
('𓐧', '', '', 'unknown', 'Unknown', 'ideographic', 'Aa25', 'Aa. Unclassified', NULL),
('𓐨', '', '', 'unknown', 'Unknown', 'determinative', 'Aa26', 'Aa. Unclassified', NULL),
('𓐩', 'nḏ', 'nj', 'unknown', 'Unknown', 'biliteral', 'Aa27', 'Aa. Unclassified', '𓈖𓆓'),
('𓐪', 'qd', 'qd', 'builder’s tool?', 'Builder’s tool?', 'biliteral', 'Aa28', 'Aa. Unclassified', '𓈎𓂧'),
('𓐫', '', '', 'var. of aa28', 'Var. of Aa28', 'other', 'Aa29', 'Aa. Unclassified', NULL),
('𓐬', '', '', 'frieze element?', 'Frieze element?', 'determinative', 'Aa30', 'Aa. Unclassified', NULL),
('𓐭', '', '', 'var. of aa30', 'Var. of Aa30', 'other', 'Aa31', 'Aa. Unclassified', NULL);
