
-- uniliterals
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group)
VALUES
('𓄿', 'ꜣ', 'a', 'vulture', 'Vulture', 'uniliteral', 'G1', 'G. Birds'),
('𓇋', 'ỉ', 'i', 'reed', 'Reed', 'uniliteral', 'M17', 'M. Trees and plants'),
('𓇌', 'y', 'Y', 'two reeds', 'Reeds', 'uniliteral', 'M17A', 'M. Trees and plants'),
('𓏭', 'y', 'y', 'dual stroke; stroke', 'Strokes', 'uniliteral', 'Z4', 'Z. Strokes, signs derived from Hieratic, geometrical figures'),
('𓂝', 'ꜥ', 'A', 'forearm; arm; palm; palm upwards', 'Forearm', 'uniliteral', 'D36', 'D. Parts of the human body'),
('𓅱', 'w', 'w', 'quail chick; quail; chick', 'Quail chick', 'uniliteral', 'G43', 'G. Birds'),
('𓏲', 'w', 'W', 'coil', 'Coil', 'uniliteral', 'Z7', 'Z. Strokes, signs derived from Hieratic, geometrical figures'),
('𓃀', 'b', 'b', 'foot', 'Foot', 'uniliteral', 'D58', 'D. Parts of the human body'),
('𓊪', 'p', 'p', 'stool', 'Stool', 'uniliteral', 'Q3', 'Q. Domestics and funerary furniture'),
('𓆑', 'f', 'f', 'horned viper; viper; horned; snake', 'Viper', 'uniliteral', 'I9', 'I. Amphibious animals, reptiles, etc.'),
('𓅓', 'm', 'm', 'owl', 'Owl', 'uniliteral', 'G17', 'G. Birds'),
('𓈖', 'n', 'n', 'ripple of water; ripple; water', 'Ripple of water', 'uniliteral', 'N35', 'N. Sky, earth, water'),
('𓂋', 'r', 'r', 'mouth', 'Mouth', 'uniliteral', 'D21', 'D. Parts of the human body'),
('𓉔', 'h', 'h', 'shelter', 'Shelter', 'uniliteral', 'O4', 'O. Buildings, parts of buildings, etc.'),
('𓎛', 'ḥ', 'H', 'twisted wick; twisted; wick of flax; flax; wick', 'Wick of flax', 'uniliteral', 'V28', 'V. Rope, fiber, baskets, bags, etc.'),
('𓐍', 'ḫ', 'x', 'placenta; sieve; ball of twine; ball; twine', 'Placenta', 'uniliteral', 'Aa1', 'Aa. Unclassified'),
('𓄡', 'ẖ', 'X', 'animal belly; belly;', 'Animal belly', 'uniliteral', 'F32', 'F. Parts of mammals'),
('𓋴', 's', 's', 'folded cloth; folded; cloth', 'Folded cloth', 'uniliteral', 'S29', 'S. Crowns, dress, staves, etc.'),
('𓊃', 's', 'z', 'door bolt; door; bolt', 'Door bolt', 'uniliteral', 'O34', 'O. Buildings, parts of buildings, etc.'),
('𓈙', 'š', 'S', 'pool', 'Pool', 'uniliteral', 'N37', 'N. Sky, earth, water'),
('𓈎', 'q', 'q', 'slope of hill; slope; hill; hill slope', 'Hill slope', 'uniliteral', 'N29', 'N. Sky, earth, water'),
('𓎡', 'k', 'k', 'basket with handle; basket; handle', 'Basket with handle', 'uniliteral', 'V31', 'V. Rope, fiber, baskets, bags, etc.'),
('𓎼', 'g', 'g', 'jar stand; jar', 'Jar Stand', 'uniliteral', 'W11', 'W. Vessels of stone and earthenware'),
('𓏏', 't', 't', 'loaf of bread; loaf; bread', 'Loaf of Bread', 'uniliteral', 'X1', 'X. Loaves and cakes'),
('𓍿', 'ṯ', 'T', 'tethering rope; tether; rope; animal tether', 'Animal Tether', 'uniliteral', 'V13', 'V. Rope, fiber, baskets, bags, etc.'),
('𓂧', 'd', 'd', 'hand', 'Hand', 'uniliteral', 'D46', 'D. Parts of the human body'),
('𓆓', 'ḏ', 'j', 'cobra; snake; cobra in repose; repose', 'Cobra', 'uniliteral', 'I10', 'I. Amphibious animals, reptiles, etc.');

-- biliterals
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓄫', 'ꜣw', 'aw', 'backbone; spinal cord; spinal; cord', 'Spinal cord', 'biliteral', 'F40', 'F. Parts of mammals', '𓄿𓅱'),
('𓊨', 'ꜣs', 'as', 'seat; throne', 'Seat', 'biliteral', 'Q1', 'Q. Domestics and funerary furniture', '𓄿𓋴'),
('𓍋', 'ꜣb', 'ab', 'chisel', 'Chisel', 'biliteral', 'U23', 'U. Agriculture, crafts, and professions', '𓄿𓃀'),
('𓃙', 'ỉb', 'ib', 'kid; goat', 'Goat', 'biliteral', 'E8', 'E. Mammals', '𓇋𓃀'),
('𓏎', 'ỉn', 'in', 'pot with legs; pot; legs', 'Pot with legs', 'biliteral', 'W25', 'W. Vessels of stone and earthenware', '𓇋𓈖'),
('𓆛', 'ỉn', 'in', 'tilapia', 'Tilapia', 'biliteral', 'K1', 'K. Fish and parts of fish', '𓇋𓈖'),
('𓁹', 'ỉr', 'ir', 'eye', 'Eye', 'biliteral', 'D4', 'D. Parts of the human body', '𓇋𓂋'),
('𓉻', 'ꜥꜣ', 'Aa', 'horizontal wooden column; horizontal; column', 'Horizontal wooden column', 'biliteral', 'O29', 'O. Buildings, parts of buildings, etc.', '𓂝𓄿'),
('𓉼', 'ꜥꜣ', 'Aa', 'vertical wooden column; vertical; column', 'Vertical wooden column', 'biliteral', 'O29A', 'O. Buildings, parts of buildings, etc.', '𓂝𓄿'),
('𓌡', 'wꜥ', 'wA', 'harpoon', 'Harpoon', 'biliteral', 'T21', 'T. Warfare, hunting, and butchery', '𓅱𓂝'),
('𓄑', 'bḥ', 'bH', 'tusk', 'Tusk', 'biliteral', 'F18', 'F. Parts of mammals', '𓃀𓎛'),
('𓉐', 'pr', 'pr', 'house', 'House', 'biliteral', 'O1', 'O. Buildings, parts of buildings, etc.', '𓊪𓂋'),
('𓌳', 'mꜣ', 'ma', 'sickle', 'Sickle', 'biliteral', 'U1', 'U. Agriculture, crafts, and professions', '𓅓𓄿'),
('𓏠', 'mn', 'mn', 'senet board; senet; board', 'Senet board', 'biliteral', 'Y5', 'Y. Writings, games, music', '𓅓𓈖'),
('𓌻', 'mr', 'mr', 'hoe', 'Hoe', 'biliteral', 'U7', 'U. Agriculture, crafts, and professions', '𓅓𓂋'),
('𓈘', 'mr', 'mr', 'canal', 'Canal', 'biliteral', 'N36', 'N. Sky, earth, water', '𓅓𓂋'),
('𓍋', 'mr', 'mr', 'chisel', 'Chisel', 'biliteral', 'U23', 'U. Agriculture, crafts, and professions', '𓅓𓂋'),
('𓄟', 'ms', 'ms', 'three skins; skins', 'Three skins tied together', 'biliteral', 'F31', 'F. Parts of mammals', '𓅓𓋴'),
('𓏌', 'nw', 'nw', 'pot', 'Pot', 'biliteral', 'W24', 'W. Vessels of stone and earthenware', '𓈖𓅱'),
('𓎟', 'nb', 'nb', 'basket', 'Basket', 'biliteral', 'V30', 'V. Rope, fiber, baskets, bags, etc.', '𓈖𓃀'),
('𓍛', 'ḥm', 'Hm', 'fuller''s club; fuller; club;', 'Fuller''s club', 'biliteral', 'U36', 'U. Agriculture, crafts, and professions', '𓎛𓅓'),
('𓈞', 'ḥm', 'Hm', 'well with ripple of water; well; water well; ripple; water', 'Well with ripple of water', 'biliteral', 'N41', 'N. Sky, earth, water', '𓎛𓅓'),
('𓁷', 'ḥr', 'Hr', 'face; head;', 'Face', 'biliteral', 'D2', 'D. Parts of the human body', '𓎛𓂋'),
('𓎿', 'ḥs', 'Hs', 'water jar; jar;', 'Water jar', 'biliteral', 'W14', 'W. Vessels of stone and earthenware', '𓎛𓋴'),
('𓌉', 'ḥḏ', 'Hj', 'mace with round head; mace;', 'Mace with round head', 'biliteral', 'T3', 'T. Warfare, hunting, and butchery', '𓎛𓆓'),
('𓆼', 'ḫꜣ', 'xa', 'lotus plant; one lotus;', 'Lotus', 'biliteral', 'M12', 'M. Trees and plants', '𓐍𓄿'),
('𓈍', 'ḫꜥ', 'xA', 'rays of sun over hill; sun over hill; ray of sun;', 'Rays of sun over hill', 'biliteral', 'N28', 'N. Sky, earth, water', '𓐍𓂝'),
('𓆱', 'ḫt', 'xt', 'branch', 'Branch', 'biliteral', 'M3', 'M. Trees and plants', '𓐍𓏏'),
('𓌨', 'ẖr', 'Xr', 'butcher''s block; butcher; block;', 'Butcher''s block', 'biliteral', 'T28', 'T. Warfare, hunting, and butchery', '𓄡𓂋'),
('𓅭', 'sꜣ', 'sa', 'pintail duck; duck;', 'Pintail duck', 'biliteral', 'G39', 'G. Birds', '𓋴𓄿'),
('𓇓', 'sw', 'sw', 'sedge;', 'Sedge', 'biliteral', 'M23', 'M. Trees and plants', '𓋴𓅱'),
('𓊗', 'sp', 'sp', 'threshing floor; floor;', 'Threshing floor', 'biliteral', 'O50', 'O. Buildings, parts of buildings, etc.', '𓋴𓊪'),
('𓌢', 'sn', 'sn', 'arrowhead; arrow;', 'Arrowhead', 'biliteral', 'T22', 'T. Warfare, hunting, and butchery', '𓋴𓈖'),
('𓏟', 'sẖ', 'sX', 'scribe''s equipment; write; sinaleira; semaforo', 'Scribe''s equipment', 'biliteral', 'Y3', 'Y. Writings, games, music', '𓋴𓄡'),
('𓄝', 'sṯ', 'sT', 'skin;', 'Cow''s skin pierced by arrow', 'biliteral', 'F29', 'F. Parts of mammals', '𓋴𓍿'),
('𓍲', 'šn', 'Sn', 'shape;', 'Rope (shape)', 'biliteral', 'V7', 'V. Rope, fiber, baskets, bags, etc.', '𓈙𓈖'),
('𓍱', 'šs', 'Ss', 'alabaster;', 'Rope (shape)', 'biliteral', 'V6', 'V. Rope, fiber, baskets, bags, etc.', '𓈙𓋴'),
('𓂓', 'kꜣ', 'ka', 'ka;', 'Ka', 'biliteral', 'D28', 'D. Parts of the human body', '𓎡𓄿'),
('𓅬', 'gb', 'gb', 'goose;', 'Goose', 'biliteral', 'G38', 'G. Birds', '𓎼𓃀'),
('𓍔', 'tꜣ', 'ta', 'kiln', 'Kiln', 'biliteral', 'U30', 'U. Agriculture, crafts, and professions', '𓏏𓄿'),
('𓇾', 'tꜣ', 'ta', 'grains;', 'Land with grains', 'biliteral', 'N16', 'N. Sky, earth, water', '𓏏𓄿'),
('𓇿', 'tꜣ', 'ta', 'land;', 'Land', 'biliteral', 'N17', 'N. Sky, earth, water', '𓏏𓄿'),
('𓅂', 'tw', 'tw', 'buzzard;', 'Buzzard', 'biliteral', 'G4', 'G. Birds', '𓏏𓅱'),
('𓍘', 'tỉ', 'ti', 'top;', 'Pestle', 'biliteral', 'U33', 'U. Agriculture, crafts, and professions', '𓏏𓇋'),
('𓁶', 'tp', 'tp', 'head;', 'Head', 'biliteral', 'D1', 'D. Parts of the human body', '𓏏𓊪'),
('𓌐', 'tp', 'tp', 'dagger;', 'Dagger', 'biliteral', 'T8', 'T. Warfare, hunting, and butchery', '𓏏𓊪'),
('𓍃', 'tm', 'tm', 'trenó;', 'Sled', 'biliteral', 'U15', 'U. Agriculture, crafts, and professions', '𓏏𓅓'),
('𓏙', 'dỉ', 'di', 'triangle; give;', 'Cone bread', 'biliteral', 'X8', 'X. Loaves and cakes', '𓂧𓇋'),
('𓂞', 'dỉ', 'di', 'forearm;', 'Forearm with cone bread', 'biliteral', 'D37', 'D. Parts of the human body', '𓂧𓇋'),
('𓍑', 'ḏꜣ', 'ja', 'forest;', 'Fire-drill', 'biliteral', 'U28', 'U. Agriculture, crafts, and professions', '𓆓𓄿'),
('𓈋', 'ḏw', 'jw', 'hills;', 'Two hills', 'biliteral', 'N26', 'N. Sky, earth, water', '𓆓𓅱'),
('𓇨', 'ḏr', 'jr', 'basket;', 'Basket of fruit', 'biliteral', 'M39', 'M. Trees and plants', '𓆓𓂋'),
('𓊽', 'ḏd', 'jd', 'column;', 'Reed column', 'biliteral', 'R11', 'R. Temple furniture and sacred emblems', '𓆓𓂧');

-- triliterals
INSERT INTO hieroglyphs (glyph, transliteration, input_transliteration, description_words, name, category, gardiner_code, gardiner_group, composing_glyphs)
VALUES
('𓉺', 'ỉwn', 'wwn', 'column;', 'Column;', 'triliteral', 'O28', 'O. Buildings, parts of buildings, etc.', '𓇋𓅱𓈖'),
('𓄔', 'ỉdn', 'wdn', 'ear of bovine; bovine ear; ear;', 'Bovine ear', 'triliteral', 'F21', 'F. Parts of mammals', '𓇋𓂧𓈖'),
('𓋹', 'ꜥnḫ', 'Anx', 'life; ankh;', 'Ankh', 'triliteral', 'S34', 'S. Crowns, dress, staves, etc.', '𓂝𓈖𓐍'),
('𓌀', 'wꜣs', 'was', 'was scepter; scepter; was; power;', 'Was scepter', 'triliteral', 'S40', 'S. Crowns, dress, staves, etc.', '𓅱𓄿𓋴'),
('𓇅', 'wꜣḏ', 'waj', 'papyrus stem; papyrus; stem;', 'Papyrus stem', 'triliteral', 'M13', 'M. Trees and plants', '𓅱𓄿𓆓'),
('𓃂', 'wꜥb', 'wAb', 'foot under vase; water flow; flow; flowing; vase; foot; pure; clean;', 'Foot under vase from which water flows', 'triliteral', 'D60', 'D. Parts of the human body', '𓅱𓂝𓃀'),
('𓄙', 'wḥm', 'wHm', 'leg of ox; ox leg; leg; bovine; cow leg; leg of cow;', 'Bovine leg', 'triliteral', 'F25', 'F. Parts of mammals', '𓅱𓎛𓅓'),
('𓄊', 'wsr', 'wsr', 'animal head; head of animal; power;', 'Power', 'triliteral', 'F12', 'F. Parts of mammals', '𓅱𓋴𓂋'),
('𓐙', 'mꜣꜥ', 'maA', 'raised platform; platform;', 'Raised platform', 'triliteral', 'Aa11', 'Aa. Unclassified', '𓅓𓄿𓂝'),
('𓄪', 'mꜣḫ', 'max', 'backbone; spinal cord; spinal; cord', 'Spinal cord', 'triliteral', 'F39', 'F. Parts of mammals', '𓅓𓄿𓐍'),
('𓋉', 'mnw', 'mnw', 'two narrow belemnites; min; menas; belemnite;', 'Emblem of Min', 'triliteral', 'R22', 'R. Temple furniture and sacred emblems', '𓅓𓈖𓅱'),
('𓋞', 'nbw', 'nbw', 'collar of beads; gold; lord;', 'Gold', 'triliteral', 'S12', 'S. Crowns, dress, staves, etc.', '𓈖𓃀𓅱'),
('𓄤', 'nfr', 'nfr', 'heart and windpipe; violão; windpipe; perfect; young; beautiful; good;', 'Perfect', 'triliteral', 'F35', 'F. Parts of mammals', '𓈖𓆑𓂋'),
('𓇑', 'nḫb', 'nxb', 'rush; nekhbet;', 'Rush', 'triliteral', 'M22', 'M. Trees and plants', '𓈖𓐍𓃀'),
('𓊹', 'nṯr', 'nTr', 'cloth on pole; pole; god; divine;', 'God', 'triliteral', 'R8', 'R. Temple furniture and sacred emblems', '𓈖𓍿𓂋'),
('𓄂', 'ḥꜣt', 'Hat', 'forepart of lion; lion;', 'Forepart of lion;', 'triliteral', 'F4', 'F. Parts of mammals', '𓎛𓄿𓏏'),
('𓋾', 'ḥqꜣ', 'Hqa', 'crook; rule; scepter; ruler;', 'Scepter', 'triliteral', 'S38', 'S. Crowns, dress, staves, etc.', '𓎛𓈎𓄿'),
('𓊵', 'ḥtp', 'Htp', 'loaf on mat; altar; offering;', 'Loaf on mat', 'triliteral', 'R4', 'R. Temple furniture and sacred emblems', '𓎛𓏏𓊪'),
('𓆣', 'ḫpr', 'xpr', 'dung beetle; beetle; scarab; khepri;', 'Scarab', 'triliteral', 'L1', 'L. Invertebrates and lesser animals', '𓐍𓊪𓂋'),
('𓄗', 'ḫpš', 'xpS', 'foreleg of ox; ox leg;', 'Ox leg', 'triliteral', 'F23', 'F. Parts of mammals', '𓐍𓊪𓈙'),
('𓏃', 'ḫnt', 'xnt', 'water jar with rack; water jar; jars;', 'Water jars', 'triliteral', 'W17', 'W. Vessels of stone and earthenware', '𓐍𓈖𓏏'),
('𓏅', 'ḫnt', 'xnt', 'water jar with rack; water jar; jars;', 'Water jars', 'triliteral', 'W18', 'W. Vessels of stone and earthenware', '𓐍𓈖𓏏'),
('𓊤', 'ḫrw', 'xrw', 'oar; voice;', 'Oar', 'triliteral', 'P8', 'P. Ships and parts of ships', '𓐍𓂋𓅱'),
('𓋨', 'ḫtm', 'xtm', 'seal with necklace; seal; necklace; torneira;', 'Seal with necklace', 'triliteral', 'S19', 'S. Crowns, dress, staves, etc.', '𓐍𓏏𓅓'),
('𓎸', 'ẖnm', 'Xnm', 'stone jug; jug;', 'Stone jug', 'triliteral', 'W9', 'W. Vessels of stone and earthenware', '𓄡𓈖𓅓'),
('𓀸', 'sꜣw', 'saw', 'shepherd; holding stick;', 'Shepherd holding stick', 'triliteral', 'A47', 'A. Man and his occupations', '𓋴𓄿𓅱'),
('𓍉', 'stp', 'stp', 'adze;', 'Adze', 'triliteral', 'U21', 'U. Agriculture, crafts, and professions', '𓋴𓏏𓊪'),
('𓋫', 'sṯt', 'sTt', 'shoulder knot; knot; shesmetet;', 'Shoulder knot', 'triliteral', 'S22', 'S. Crowns, dress, staves, etc.', '𓋴𓍿𓏏'),
('𓇗', 'šmꜥ', 'SmA', 'flowering sedge; sedge; flowering rush; rush;', 'Flowering rush', 'triliteral', 'M26', 'M. Trees and plants', '𓈙𓅓𓂝'),
('𓍁', 'šnꜥ', 'SnA', 'plow;', 'Plow', 'triliteral', 'U13', 'U. Agriculture, crafts, and professions', '𓈙𓈖𓂝'),
('𓏂', 'qbḥ', 'qbH', 'jar;', 'Water jar with rack', 'triliteral', 'W16', 'W. Vessels of stone and earthenware', '𓈎𓃀𓎛'),
('𓇼', 'dwꜣ', 'dwa', '5;', 'Star', 'triliteral', 'N14', 'N. Sky, earth, water', '𓂧𓅱𓄿'),
('𓂦', 'ḏsr', 'jsr', 'powerstick;', 'Arm with wand', 'triliteral', 'D45', 'D. Parts of the human body', '𓆓𓋴𓂋');
